### PR TITLE
Update README.md for mainnet params

### PR DESCRIPTION
**Pull request by f8-ptrk**
update mainent boostrap peer list to current lotus/v1.15.2 branch ones

### CODE REVIEW

**Comment by jennijuju** [comment]
need to update to release/v1.26.0 ones

**Comment by smagdali** [comment]
So they should be these instead? 
https://github.com/filecoin-project/lotus/blob/release/v1.26.0/build/bootstrap/mainnet.pi 

btw there was an obviously typo 'bootstarp' on the current commit.

**Comment by eshon** [comment]
@f8-ptrk 
- Why is it necessary to list bootstrap peers in a separate place like the Filecoin Docs?
  - Won't we always need to keep updating this page? 
  - It's hard to keep synced with new update unless actually written into a Lotus release process checklist
  - Eth Docs just [link](https://ethereum.org/en/developers/docs/nodes-and-clients/bootnodes/#available-bootnodes) to what's on master
     - Why can't we just do the same? It's not 100% perfect but linking to https://github.com/filecoin-project/lotus/blob/master/build/bootstrap/mainnet.pi seems fine

**Comment by eshon** [comment]
@f8-ptrk - Why pull the Lotus code? Why not just link to it from the Docs? Like this:

"Bootstrap peers for current mainnet can be found at:

`https://github.com/filecoin-project/lotus/blob/release/[latest release]/build/bootstrap/mainnet.pi`

The latest release can be found at https://github.com/filecoin-project/lotus/releases/latest/

Is that sufficient?

**Comment by eshon** [comment]
Replaced by https://github.com/filecoin-project/filecoin-docs/pull/2265

**Pull request closed without merging**
