### PR TITLE
Adds an Oracle page into `smart-contracts/advanced`.

### LINKED ISSUE #2049: [Request]: add oracle to smart contract section
### Request type

New content

### Describe the issue.

We should add core Defi infrastructure supporting FVM into docs. It would be easier for projects or devs to find relative information if they are building on FVM.  

Oracles support FVM:
- Pyth Network
- Tellor

The raw material provided by the product team:  https://docs.google.com/document/d/1ENNdp6OLI95u5YRRHSK90n4fIpSZtwkZ6U_R5J0imt8/edit

### Is there any other information we need to know?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by longfeiWan9**
close #2049

### CODE REVIEW

**Comment by longfeiWan9** [comment]
@honghaoq can you please also review this page for Oracles as well?

**Comment by honghaoq** [comment]
looks great, ty both!

**Comment by honghaoq** [comment]
@longfeiWan9 this only covers oracle though, can we add the bridges documentation too? (I think that's the last missing bot, we can add AMM in the future after sushi launches)

**Comment by longfeiWan9** [comment]
>this only covers oracle though, can we add the bridges documentation too? (I think that's the last missing bot, we can add AMM in the future after sushi launches)

@honghaoq I have created separate issues for wFIL, Oracle and Bridge.

- [ ] wFIL - https://github.com/filecoin-project/filecoin-docs/issues/2041
- [ ] Oracle - https://github.com/filecoin-project/filecoin-docs/issues/2049
- [ ] bridge - https://github.com/filecoin-project/filecoin-docs/issues/2048

I will create a PR to add bridge soon.

**Comment by longfeiWan9** [comment]
@johnnymatthews Thank you for fixing my gramma.  👍

**Pull request merged**
