### PR TITLE
update docs based on new PR with LOTUS_MARKETS_PATH

### PR DESCRIPTION
**Pull request by nonsense**
This PR is updating docs, with respect to https://github.com/filecoin-project/lotus/pull/6936

We are also updating commands and instructions based on feedback from miners.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/mine/lotus/split-markets-miners.md`:
- A comma may be missing after the conjunctive/linking adverb ‘Currently’.
  ```
  ... subsystems in the lotus-miner process. Currently there are 4 subsystems, th...
                                             ^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...istinct types of lotus-miner nodes: The markets node - a lotus-miner process...
                                             ^^^^^^^
  ```
- The preposition ‘for’ seems more likely in this position.
  ```
  ...ode - a lotus-miner process responsible to handling the storage market subsy...
                                             ^^
  ```
- An apostrophe may be missing.
  ```
  ...ode is started with configuration for a markets node, it includes a libp2p n...
                                             ^^^^^^^
  ```
- The word “backup” is a noun. The verb is spelled with a space.
  ```
  ... the monolith miner process, you should backup your miner's metadata reposit...
                                             ^^^^^^
  ```
- Consider a shorter alternative to avoid wordiness.
  ```
  ...the LOTUS_BACKUP_BASE_PATH env variable in order to do that. # Splitting the...
                                             ^^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...ou need to create a config.toml for the markets node, and have it ready for ...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...ve it ready for the next step. For more information see configuration usage ...
                                             ^^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...proving node on the same machine as the markets node, make sure that their l...
                                             ^^^^^^^
  ```
- Did you mean: “By default,”?
  ```
  ...sure that their listeners do not clash. By default the lotus-miner API serve...
                                             ^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ... you adjust the [Libp2p] section on the markets node accordingly - it needs ...
                                             ^^^^^^^
  ```
- It seems likely that a singular genitive (’s) apostrophe is missing.
  ```
  ...ning a Libp2p node. # 3. Initialising a markets service repository Create au...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  .... This performs a one-time setup of the markets node. Part of that setup inc...
                                             ^^^^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...f that setup includes updating the peer id in the miner actor by submitting ...
                                             ^^
  ```
- An apostrophe may be missing.
  ```
  ...able! This command should be run on the markets miner instance host, as it i...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...er instance host, as it is creating the markets miner instance repository, a...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...aling/proving miner process without the markets subsystem Update your config...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...oving miner process without the markets subsystem Update your config.toml an...
                                             ^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...TH environment variable! # 6. Start the markets miner process with the marke...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...tart the markets miner process with the markets subsystem # Interacting with...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...he mining/sealing/proving miner and the markets miner, in your run-commands ...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ..., for example: Now that you have both a markets miner process and a mining/s...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...miner info Get the peer identity of the markets miner process Get a list of ...
                                             ^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...r identity of the markets miner process Get a list of storage deals from the...
                                             ^^^
  ```
- An apostrophe may be missing.
  ```
  ...ss Get a list of storage deals from the markets miner process Get a list of ...
                                             ^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ge deals from the markets miner process Get a list of sectors from the minin...
                                             ^^^
  ```
- An apostrophe may be missing.
  ```
  ...cly exposed, as we will be enabling the markets subsystem on it. In the mini...
                                             ^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ml and set EnableMarkets option to true Move back the DAG store directory to...
                                             ^^^^
  ```
- An apostrophe may be missing.
  ```
  ...s it was changed to the identity of the markets node during the initialising...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...g/proving node, which now also runs the markets subsystem, i.e. currently al...
                                             ^^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

- Check of `docs/build/estuary.md` came back clean!
### `docs/build/get-started.md`:
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...he Filecoin Network by abstracting away some of the complex workflows and re...
                                             ^^^^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...a node or directly call a Lotus daemon! TIP Want to speed up your developmen...
                                             ^^^
  ```
- A word may be missing after ‘a’.
  ```
  ...Infura API. Create a Node.js script to: a. Check if a given string is a vali...
                                             ^^
  ```
- ‘to’ seems less likely than ‘the’.
  ```
  ...fura project ID and project secret into to user and pass fields: Enter your ...
                                             ^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...e, and the method you want to call. Set id as 0 and jsonrpc as 2.0: Make sur...
                                             ^^
  ```
- Possibly missing comma found.
  ```
  ...that a given string is a valid Filecoin address but doesn't do much else. Le...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ... from Infura will be blank: # Script so far Here's what your script should l...
                                             ^^^
  ```

### `docs/mine/lotus/split-markets-miners.md`:
- A comma may be missing after the conjunctive/linking adverb ‘Currently’.
  ```
  ... subsystems in the lotus-miner process. Currently there are 4 subsystems, th...
                                             ^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...istinct types of lotus-miner nodes: The markets node - a lotus-miner process...
                                             ^^^^^^^
  ```
- The preposition ‘for’ seems more likely in this position.
  ```
  ...ode - a lotus-miner process responsible to handling the storage market subsy...
                                             ^^
  ```
- An apostrophe may be missing.
  ```
  ...ode is started with configuration for a markets node, it includes a libp2p n...
                                             ^^^^^^^
  ```
- The word “backup” is a noun. The verb is spelled with a space.
  ```
  ... the monolith miner process, you should backup your miner's metadata reposit...
                                             ^^^^^^
  ```
- Consider a shorter alternative to avoid wordiness.
  ```
  ...the LOTUS_BACKUP_BASE_PATH env variable in order to do that. # Splitting the...
                                             ^^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...ou need to create a config.toml for the markets node, and have it ready for ...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...ve it ready for the next step. For more information see configuration usage ...
                                             ^^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...proving node on the same machine as the markets node, make sure that their l...
                                             ^^^^^^^
  ```
- Did you mean: “By default,”?
  ```
  ...sure that their listeners do not clash. By default the lotus-miner API serve...
                                             ^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ... you adjust the [Libp2p] section on the markets node accordingly - it needs ...
                                             ^^^^^^^
  ```
- It seems likely that a singular genitive (’s) apostrophe is missing.
  ```
  ...ning a Libp2p node. # 3. Initialising a markets service repository Create au...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  .... This performs a one-time setup of the markets node. Part of that setup inc...
                                             ^^^^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...f that setup includes updating the peer id in the miner actor by submitting ...
                                             ^^
  ```
- An apostrophe may be missing.
  ```
  ...able! This command should be run on the markets miner instance host, as it i...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...er instance host, as it is creating the markets miner instance repository, a...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...aling/proving miner process without the markets subsystem Update your config...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...oving miner process without the markets subsystem Update your config.toml an...
                                             ^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...TH environment variable! # 6. Start the markets miner process with the marke...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...tart the markets miner process with the markets subsystem # Interacting with...
                                             ^^^^^^^
  ```
- Consider a shorter alternative to avoid wordiness.
  ```
  ...rocess with the --call-on-markets flag. In order to take advantage of this f...
                                             ^^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...he mining/sealing/proving miner and the markets miner, in your run-commands ...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ..., for example: Now that you have both a markets miner process and a mining/s...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...miner info Get the peer identity of the markets miner process Get a list of ...
                                             ^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...r identity of the markets miner process Get a list of storage deals from the...
                                             ^^^
  ```
- An apostrophe may be missing.
  ```
  ...ss Get a list of storage deals from the markets miner process Get a list of ...
                                             ^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ge deals from the markets miner process Get a list of sectors from the minin...
                                             ^^^
  ```
- An apostrophe may be missing.
  ```
  ...cly exposed, as we will be enabling the markets subsystem on it. In the mini...
                                             ^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ml and set EnableMarkets option to true Move back the DAG store directory to...
                                             ^^^^
  ```
- An apostrophe may be missing.
  ```
  ...s it was changed to the identity of the markets node during the initialising...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...g/proving node, which now also runs the markets subsystem, i.e. currently al...
                                             ^^^^^^^
  ```


### `docs/store/estuary.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  http://slingshot.filecoin.io/
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... on the Filecoin network: Go to Estuary.tech  (opens new window) and log in....
                                             ^^^^
  ```
- This phrase is duplicated. You should probably leave only “Your Data”.
  ```
  ... stored on Filecoin Network. # Retrieve Your Data Your data is retrievable a...
                                             ^^^^^^^^^^^^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...d you will get the data at any minute!  TIP Your data is retrievable even it...
                                             ^^^
  ```
- Using many exclamation marks might seem excessive (in this case: 4 exclamation marks for a text that’s 2379 characters long)
  ```
  ...ink under RETRIEVAL CID to get your data! # Additional resources Estuary Git...
                                             ^
  ```
- The official name of this software platform is spelled with a capital “H”.
  ```
  ...ur data! # Additional resources Estuary Github repository  (opens new window...
                                             ^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

- Check of `docs/build/estuary.md` came back clean!
### `docs/build/get-started.md`:
- The following link returned HTTP status code 302 (Found):
  https://nodejs.org/
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...he Filecoin Network by abstracting away some of the complex workflows and re...
                                             ^^^^^^^^^^^
  ```
- The word “sign-up” is a noun. The verb is spelled with a white space.
  ```
  ...NG The Infura API requires all users to sign-up to a waitlist to get access ...
                                             ^^^^^^^
  ```
- A word may be missing after ‘a’.
  ```
  ...Infura API. Create a Node.js script to: a. Check if a given string is a vali...
                                             ^^
  ```
- ‘to’ seems less likely than ‘the’.
  ```
  ...fura project ID and project secret into to user and pass fields: Enter your ...
                                             ^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...e, and the method you want to call. Set id as 0 and jsonrpc as 2.0: Make sur...
                                             ^^
  ```
- Possibly missing comma found.
  ```
  ...that a given string is a valid Filecoin address but doesn't do much else. Le...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ... from Infura will be blank: # Script so far Here's what your script should l...
                                             ^^^
  ```

### `docs/mine/lotus/split-markets-miners.md`:
- A comma may be missing after the conjunctive/linking adverb ‘Currently’.
  ```
  ... subsystems in the lotus-miner process. Currently there are 4 subsystems, th...
                                             ^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...istinct types of lotus-miner nodes: The markets node - a lotus-miner process...
                                             ^^^^^^^
  ```
- The preposition ‘for’ seems more likely in this position.
  ```
  ...ode - a lotus-miner process responsible to handling the storage market subsy...
                                             ^^
  ```
- An apostrophe may be missing.
  ```
  ...ode is started with configuration for a markets node, it includes a libp2p n...
                                             ^^^^^^^
  ```
- The word “backup” is a noun. The verb is spelled with a space.
  ```
  ... the monolith miner process, you should backup your miner's metadata reposit...
                                             ^^^^^^
  ```
- Consider a shorter alternative to avoid wordiness.
  ```
  ...the LOTUS_BACKUP_BASE_PATH env variable in order to do that. # Splitting the...
                                             ^^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...ed to create a seed config.toml for the markets node, and have it ready for ...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...ve it ready for the next step. For more information see configuration usage ...
                                             ^^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...proving node on the same machine as the markets node, make sure that their l...
                                             ^^^^^^^
  ```
- Did you mean: “By default,”?
  ```
  ...sure that their listeners do not clash. By default the lotus-miner API serve...
                                             ^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ... you adjust the [Libp2p] section on the markets node accordingly - it needs ...
                                             ^^^^^^^
  ```
- It seems likely that a singular genitive (’s) apostrophe is missing.
  ```
  ...ning a Libp2p node. # 3. Initialising a markets service repository Create au...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  .... This performs a one-time setup of the markets node. Part of that setup inc...
                                             ^^^^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...f that setup includes updating the peer id in the miner actor by submitting ...
                                             ^^
  ```
- An apostrophe may be missing.
  ```
  ...able! This command should be run on the markets miner instance host, as it i...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...er instance host, as it is creating the markets miner instance repository, a...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...aling/proving miner process without the markets subsystem Update your config...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...oving miner process without the markets subsystem Update your config.toml an...
                                             ^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...TH environment variable! # 6. Start the markets miner process with the marke...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...tart the markets miner process with the markets subsystem # Interacting with...
                                             ^^^^^^^
  ```
- Consider a shorter alternative to avoid wordiness.
  ```
  ...rocess with the --call-on-markets flag. In order to take advantage of this f...
                                             ^^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...he mining/sealing/proving miner and the markets miner, in your run-commands ...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ..., for example: Now that you have both a markets miner process and a mining/s...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...miner info Get the peer identity of the markets miner process Get a list of ...
                                             ^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...r identity of the markets miner process Get a list of storage deals from the...
                                             ^^^
  ```
- An apostrophe may be missing.
  ```
  ...ss Get a list of storage deals from the markets miner process Get a list of ...
                                             ^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ge deals from the markets miner process Get a list of sectors from the minin...
                                             ^^^
  ```
- An apostrophe may be missing.
  ```
  ...cly exposed, as we will be enabling the markets subsystem on it. In the mini...
                                             ^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ml and set EnableMarkets option to true Move back the DAG store directory to...
                                             ^^^^
  ```
- An apostrophe may be missing.
  ```
  ...s it was changed to the identity of the markets node during the initialising...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...g/proving node, which now also runs the markets subsystem, i.e. currently al...
                                             ^^^^^^^
  ```


### `docs/store/estuary.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  http://slingshot.filecoin.io/
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... on the Filecoin network: Go to Estuary.tech  (opens new window) and log in....
                                             ^^^^
  ```
- This phrase is duplicated. You should probably leave only “Your Data”.
  ```
  ... stored on Filecoin Network. # Retrieve Your Data Your data is retrievable a...
                                             ^^^^^^^^^^^^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...d you will get the data at any minute!  TIP Your data is retrievable even it...
                                             ^^^
  ```
- Using many exclamation marks might seem excessive (in this case: 4 exclamation marks for a text that’s 2424 characters long)
  ```
  ...ink under RETRIEVAL CID to get your data! # Additional resources Estuary Git...
                                             ^
  ```
- The official name of this software platform is spelled with a capital “H”.
  ```
  ...ur data! # Additional resources Estuary Github repository  (opens new window...
                                             ^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

- Check of `docs/build/estuary.md` came back clean!
### `docs/build/get-started.md`:
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...he Filecoin Network by abstracting away some of the complex workflows and re...
                                             ^^^^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...a node or directly call a Lotus daemon! TIP Want to speed up your developmen...
                                             ^^^
  ```
- A word may be missing after ‘a’.
  ```
  ...Infura API. Create a Node.js script to: a. Check if a given string is a vali...
                                             ^^
  ```
- ‘to’ seems less likely than ‘the’.
  ```
  ...fura project ID and project secret into to user and pass fields: Enter your ...
                                             ^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...e, and the method you want to call. Set id as 0 and jsonrpc as 2.0: Make sur...
                                             ^^
  ```
- Possibly missing comma found.
  ```
  ...that a given string is a valid Filecoin address but doesn't do much else. Le...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ... from Infura will be blank: # Script so far Here's what your script should l...
                                             ^^^
  ```

### `docs/mine/lotus/split-markets-miners.md`:
- A comma may be missing after the conjunctive/linking adverb ‘Currently’.
  ```
  ... subsystems in the lotus-miner process. Currently there are 4 subsystems, th...
                                             ^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...istinct types of lotus-miner nodes: The markets node - a lotus-miner process...
                                             ^^^^^^^
  ```
- The preposition ‘for’ seems more likely in this position.
  ```
  ...ode - a lotus-miner process responsible to handling the storage market subsy...
                                             ^^
  ```
- An apostrophe may be missing.
  ```
  ...ode is started with configuration for a markets node, it includes a libp2p n...
                                             ^^^^^^^
  ```
- The word “backup” is a noun. The verb is spelled with a space.
  ```
  ... the monolith miner process, you should backup your miner's metadata reposit...
                                             ^^^^^^
  ```
- Consider a shorter alternative to avoid wordiness.
  ```
  ...the LOTUS_BACKUP_BASE_PATH env variable in order to do that. # Splitting the...
                                             ^^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...ed to create a seed config.toml for the markets node, and have it ready for ...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...ve it ready for the next step. For more information see configuration usage ...
                                             ^^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...proving node on the same machine as the markets node, make sure that their l...
                                             ^^^^^^^
  ```
- Did you mean: “By default,”?
  ```
  ...sure that their listeners do not clash. By default the lotus-miner API serve...
                                             ^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ... you adjust the [Libp2p] section on the markets node accordingly - it needs ...
                                             ^^^^^^^
  ```
- Possibly missing preposition found.
  ```
  ...itialising a markets service repository Create authentication tokens for the...
                                             ^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...ry Create authentication tokens for the markets node. This is an online oper...
                                             ^^^^^^^
  ```
- Possibly missing preposition found.
  ```
  ...se you move its API to another IP:PORT) Initialise the market node. This per...
                                             ^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  .... This performs a one-time setup of the markets node. Part of that setup inc...
                                             ^^^^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...f that setup includes updating the peer id in the miner actor by submitting ...
                                             ^^
  ```
- An apostrophe may be missing.
  ```
  ...able! This command should be run on the markets miner instance host, as it i...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...er instance host, as it is creating the markets miner instance repository, a...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...aling/proving miner process without the markets subsystem Update your config...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...oving miner process without the markets subsystem Update your config.toml an...
                                             ^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...TH environment variable! # 6. Start the markets miner process with the marke...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...tart the markets miner process with the markets subsystem # Interacting with...
                                             ^^^^^^^
  ```
- Consider a shorter alternative to avoid wordiness.
  ```
  ...rocess with the --call-on-markets flag. In order to take advantage of this f...
                                             ^^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...he mining/sealing/proving miner and the markets miner, in your run-commands ...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ..., for example: Now that you have both a markets miner process and a mining/s...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...miner info Get the peer identity of the markets miner process Get a list of ...
                                             ^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...r identity of the markets miner process Get a list of storage deals from the...
                                             ^^^
  ```
- An apostrophe may be missing.
  ```
  ...ss Get a list of storage deals from the markets miner process Get a list of ...
                                             ^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ge deals from the markets miner process Get a list of sectors from the minin...
                                             ^^^
  ```
- An apostrophe may be missing.
  ```
  ...cly exposed, as we will be enabling the markets subsystem on it. In the mini...
                                             ^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ml and set EnableMarkets option to true Move back the DAG store directory to...
                                             ^^^^
  ```
- An apostrophe may be missing.
  ```
  ...s it was changed to the identity of the markets node during the initialising...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...g/proving node, which now also runs the markets subsystem, i.e. currently al...
                                             ^^^^^^^
  ```


### `docs/store/estuary.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  http://slingshot.filecoin.io/
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... on the Filecoin network: Go to Estuary.tech  (opens new window) and log in....
                                             ^^^^
  ```
- This phrase is duplicated. You should probably leave only “Your Data”.
  ```
  ... stored on Filecoin Network. # Retrieve Your Data Your data is retrievable a...
                                             ^^^^^^^^^^^^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...d you will get the data at any minute!  TIP Your data is retrievable even it...
                                             ^^^
  ```
- Using many exclamation marks might seem excessive (in this case: 4 exclamation marks for a text that’s 2416 characters long)
  ```
  ...ink under RETRIEVAL CID to get your data! # Additional resources Estuary Git...
                                             ^
  ```
- The official name of this software platform is spelled with a capital “H”.
  ```
  ...ur data! # Additional resources Estuary Github repository  (opens new window...
                                             ^^^^^^
  ```

**Review by jacobheun — APPROVED** [review]
These are solid improvements. Will look at iterating on this next week to roll up env variables and new directories into a prep step at the beginning per feedback from miners.

**Pull request merged**
