### PR TITLE
Issue 1561 - How to call a built-in actor

### PR DESCRIPTION
**Pull request by ElPaisano**
Creates `content/en/developers/smart-contracts/how-tos/call-built-in-actor/index.md` to address https://github.com/filecoin-project/filecoin-docs/issues/1561

### CODE REVIEW

**Comment by ElPaisano** [comment]
@johnnymatthews this is ready for review

**Comment by johnnymatthews** [comment]
This is great! Nice work mate. 

Is there a UX reason why the actor methods aren't in alphabetical order? If not, can you set them to be in alphabetical order?

image

Other than that, this PR is good to merge.

**Review by johnnymatthews — APPROVED** [review]

**Comment by johnnymatthews** [comment]
Have you? 

image

**Comment by johnnymatthews** [comment]
Oh I see! You've moved the main built-in actors around. Sorry, I should've been clearer. I meant the individual methods in the tables.

**Comment by ElPaisano** [comment]
> Oh I see! You've moved the main built-in actors around. Sorry, I should've been clearer. I meant the individual methods in the tables.

ah whoops methods sorted in https://github.com/filecoin-project/filecoin-docs/pull/1747/commits/c512c6b3c3128eec4c42c5793dd5d387876f3641

**Review by johnnymatthews — APPROVED** [review]

**Pull request merged**
