### PR TITLE
Adds detail to provider workflow

### PR DESCRIPTION
**Pull request by Annamarie2019**
Revises introduction and Types of Providers
Adds (with links for more detail):
- Hardware requirements (are these required of retrieval providers as well?)
- Install Lotus application
- Storage provider collateral
- Gas fees
- Storage provider deals
- Data Transfer
- Sealing (PoRep)
- PoSt
- Retrieval provider role
- zk-SNARKs
- Slashing
- Storage provider power and rewards
- Verified storage deals (Filecoin Plus)
- Retrieval provider fees
- What to do next and links to get started

### CODE REVIEW

**Comment by Annamarie2019** [comment]
@johnnymatthews I don't see access to the conflicts to resolve. Please let me know how I can resolve them. I removed three proposed images in case they were the problem, but it doesn't seem to have fixed the conflict.

**Comment by johnnymatthews** [comment]
Ok, that should fix the merge conflict. In term of content, this is good! There are a few errors that could be picked up by an error checker though. Try running this page through Grammarly and fixing the issues it pops up.

**Comment by Annamarie2019** [comment]
@johnnymatthews I ran it through Grammarly and made some other changes (like name and link for the CID gravity app https://www.cidgravity.com/ and added images back ) but my push is rejected:
Screen Shot 2022-04-11 at 9 10 12 AM

**Comment by Annamarie2019** [comment]
@johnnymatthews  One more thing before I say it's done: There seem to be two versions of the same file in the Files Changed tab. (One before the images and one after.) I think that happened when I thought there were conflicts. The second file shows the latest version.

**Review by johnnymatthews — APPROVED** [review]
Looks good!

**Pull request merged**
