### PR TITLE
Add/re outbound links to web3 storage

### PR DESCRIPTION
**Pull request by johnnymatthews**

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Review by whyrusleeping — APPROVED** [review]
LGTM

**Review by atopal — APPROVED** [review]
Thank you, Johnny!

**Comment by terichadbourne** [comment]
This all looks great, but I think your'e now missing the bulk of the needed edits that you'd taken care of in the previous PR. Will ping you to clarify.

**Comment by johnnymatthews** [comment]
I missed off the callouts like an idiot. Just added them in. Please re-review when you get a sec.

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

### `docs/build/get-started.md`:
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...he Filecoin Network by abstracting away some of the complex workflows and re...
                                             ^^^^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...a node or directly call a Lotus daemon! TIP Want to speed up your developmen...
                                             ^^^
  ```
- A word may be missing after ‘a’.
  ```
  ...Infura API. Create a Node.js script to: a. Check if a given string is a vali...
                                             ^^
  ```
- ‘to’ seems less likely than ‘the’.
  ```
  ...fura project ID and project secret into to user and pass fields: Enter your ...
                                             ^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...e, and the method you want to call. Set id as 0 and jsonrpc as 2.0: Make sur...
                                             ^^
  ```
- Possibly missing comma found.
  ```
  ...that a given string is a valid Filecoin address but doesn't do much else. Le...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ... from Infura will be blank: # Script so far Here's what your script should l...
                                             ^^^
  ```

**Review by whyrusleeping — APPROVED** [review]

**Comment by terichadbourne** [comment]
You can hold off on the re-review. Still trying to get Git to revert our reversions. 😂

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

- Check of `docs/build/estuary.md` came back clean!
### `docs/build/get-started.md`:
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...he Filecoin Network by abstracting away some of the complex workflows and re...
                                             ^^^^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...a node or directly call a Lotus daemon! TIP Want to speed up your developmen...
                                             ^^^
  ```
- A word may be missing after ‘a’.
  ```
  ...Infura API. Create a Node.js script to: a. Check if a given string is a vali...
                                             ^^
  ```
- ‘to’ seems less likely than ‘the’.
  ```
  ...fura project ID and project secret into to user and pass fields: Enter your ...
                                             ^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...e, and the method you want to call. Set id as 0 and jsonrpc as 2.0: Make sur...
                                             ^^
  ```
- Possibly missing comma found.
  ```
  ...that a given string is a valid Filecoin address but doesn't do much else. Le...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ... from Infura will be blank: # Script so far Here's what your script should l...
                                             ^^^
  ```



### `docs/store/estuary.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  http://slingshot.filecoin.io/
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... on the Filecoin network: Go to Estuary.tech  (opens new window) and log in....
                                             ^^^^
  ```
- This phrase is duplicated. You should probably leave only “Your Data”.
  ```
  ... stored on Filecoin Network. # Retrieve Your Data Your data is retrievable a...
                                             ^^^^^^^^^^^^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...d you will get the data at any minute!  TIP Your data is retrievable even it...
                                             ^^^
  ```
- Using many exclamation marks might seem excessive (in this case: 4 exclamation marks for a text that’s 2416 characters long)
  ```
  ...ink under RETRIEVAL CID to get your data! # Additional resources Estuary Git...
                                             ^
  ```
- The official name of this software platform is spelled with a capital “H”.
  ```
  ...ur data! # Additional resources Estuary Github repository  (opens new window...
                                             ^^^^^^
  ```

**Review by terichadbourne — APPROVED** [review]
Thanks @johnnymatthews! @whyrusleeping Can you please give this one last look? We've succeeded at reinstating the last batch of edits. (I'm skipping Kadir because he already approved it with these edits in the previous PR.)

**Review by whyrusleeping — APPROVED** [review]
Thanks @johnnymatthews !

**Pull request merged**
