### PR TITLE
add config options for batching deal publish

### PR DESCRIPTION
**Pull request by dirkmc**

### CODE REVIEW

**Review by jennijuju — APPROVED** [review]

**Comment by jennijuju** [comment]
@johnnymatthews could you please merge this when v1.4.2 is released?

**Comment by PatrickDeuse** [comment]
@dirkmc the 1h (in the example) applies to the first or the last message added to the "batch"

msg1: 7:30 ---> "batch wait" until 8:30
msg2: 7:45 ---> "batch wait" until ???

**Comment by dirkmc** [comment]
@PatrickDeuse I added some more explanation. Is it clear now?

**Comment by PatrickDeuse** [comment]
@dirkmc crystal clear.

there must be a natural limit on how many deals we can put inside to get the message on chain. be it a maxInt we hit somewhere...

we will figure it out as soon as the calibnet is back on the battlefield

**Comment by ribasushi** [comment]
@dirkmc how does this interface with palcement-into-sectors: that is when does the sector/piece assignment happen when the batch-publish completes, or does it happen on deal-acceptance? ( don't have a working miner to check this locally )

**Comment by PatrickDeuse** [comment]
@ribasushi the placement into sectors is done after the publishdeals message hits the chain.

technically "when the batch-publish completes" and "deal-acceptance" are the same thing! see my, kind of, "don't touch my money" rant here:

https://github.com/filecoin-project/lotus/issues/5444

**Pull request merged**
