### PR TITLE
Issue 1698: Built-in actors

### PR DESCRIPTION
**Pull request by ElPaisano**
Addresses https://github.com/filecoin-project/filecoin-docs/issues/1698

### CODE REVIEW

**Comment by ElPaisano** [comment]
@johnnymatthews can I get a checkpoint review on this one?

My approach is to 1) integrate content relevant recently pushed content to `main` (https://github.com/filecoin-project/filecoin-docs/commit/55b3be7485e0accf339d01bfd20dba7b757c9d4f, https://github.com/filecoin-project/filecoin-docs/pull/1747 and https://github.com/filecoin-project/filecoin-docs/pull/1693) and 2) split the content into the following structure, keeping in mind the points listed on #1698 

**Conceptual page:**
- [ ] What the built-in actors are.
- [ ] The two different API _types*_ available to devs (and a link out to the dev page):

**Dev page**
- [ ] How developers can access/invoke the built-in actors API
- [ ] How they're different to other Filecoin APIs.
    - [ ] (How to use) Protocol API
    - [ ] (How to use) Zondax/Filecoin.sol API
    
Does this structure fit with the overall vibe of the new layout? I din't want to try and cram a ton of info into one page

**Comment by johnnymatthews** [comment]
Yeah that works nicely @ElPaisano. Let's go with that.

**Comment by ElPaisano** [comment]
@johnnymatthews this is ready for review. 

I can't see the build preview for some reason. Is that only enabled for PRs onto `main`?

**Comment by johnnymatthews** [comment]
> I can't see the build preview for some reason. Is that only enabled for PRs onto main?

Yeah, Fleek was freaking out so I turned off the previews to get them working on `main` again.

> Also, this file [...] showed up

Ya, there's _lots_ of moving parts right now. Things will settle down this evening though.

I'll review this now.

**Pull request merged**
