### PR TITLE
Add thirdweb to relevent sections of docs

### PR DESCRIPTION
**Pull request by atharvadeosthale**
This PR adds thirdweb tools to the relevant section of the documentation. Please let me know if you have any questions; thanks!

### CODE REVIEW

**Comment by johnnymatthews** [comment]
Hey @atharvadeosthale, sorry for the delay in getting to this PR.

This tutorial doesn't seem Filecoin specific, and might not be suitable for the Filecoin docs. Does Thirdweb have a specific API or SDK for Filecoin builders?

**Comment by saminacodes** [comment]
Our SDKs are compatible with each EVM chains but we highlight them individually for builders coming from specific chains via how you configure your project. There is no specific API. Curious to understand why it is not suitable for the Filecoin docs- is there any way we can modify the content to fit?

**Comment by johnnymatthews** [comment]
> is there any way we can modify the content to fit?

It'd be great if this tutorial was specific to Filecoin -- if it showed something the reader can only do with Filecoin and no other blockchain. Storing some data, for example. Or getting data from a specific on-chain deal.

**Comment by saminacodes** [comment]
Gotcha! Appreciate the clarification.

We won't be able to create that specific content at this time. Maybe we can explore it later down the line.

We can cancel this draft for the time being.

**Pull request closed without merging**
