### PR TITLE
EOracle Docs

### PR DESCRIPTION
**Pull request by xBalbinus**

### CODE REVIEW

**Comment by xBalbinus** [comment]
Contains some changes to multicall3 docs to include them into the ToC

**Comment by smagdali** [comment]
This is failing because https://docs.eoracle.io/ doesn't appear to exist?

**Comment by xBalbinus** [comment]
Yes and there are also other pending changes from EOracle's side.

**Comment by xBalbinus** [comment]
Added the requested changes from EOracle's side

**Pull request merged**
