### PR TITLE
Create GH Action for CI checks (automates grammar, image optimization, build, and link checking)

### PR DESCRIPTION
**Pull request by johndmulhausen**
Checks for:
- Grammar optimization (via LanguageTools)
- Image compression (via optipng and jpegoptim)
- Outbound link checking (Python's Requests library)
- Vuepress build failure

### CODE REVIEW

**Comment by johndmulhausen** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```

> filecoin-docs@1.0.0 docs:build /home/runner/work/filecoin-docs/filecoin-docs
> npm run docs:links && vuepress build docs


> filecoin-docs@1.0.0 docs:links /home/runner/work/filecoin-docs/filecoin-docs
> vuepress check-md docs


Checking markdown...
Executes with --fix to fix automatically
```
- No markdown files were changed, so no page checks were run!

**Comment by johndmulhausen** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```

> filecoin-docs@1.0.0 docs:build /home/runner/work/filecoin-docs/filecoin-docs
> npm run docs:links && vuepress build docs


> filecoin-docs@1.0.0 docs:links /home/runner/work/filecoin-docs/filecoin-docs
> vuepress check-md docs


Checking markdown...

1 dead links was found

  File is not found: [Lotus lite-node](../../../build/lotus/lotus-lite) (/home/runner/work/filecoin-docs/filecoin-docs/docs/get-started/lotus/installation.md:191:165)

Executes with --fix to fix automatically

Checking failed

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:links: `vuepress check-md docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:links script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-20T15_18_18_890Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:build: `npm run docs:links && vuepress build docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-20T15_18_18_911Z-debug.log
```
- No markdown files were changed, so no page checks were run!

**Comment by johndmulhausen** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```

> filecoin-docs@1.0.0 docs:build /home/runner/work/filecoin-docs/filecoin-docs
> npm run docs:links && vuepress build docs


> filecoin-docs@1.0.0 docs:links /home/runner/work/filecoin-docs/filecoin-docs
> vuepress check-md docs


Checking markdown...

1 dead links was found

  File is not found: [Lotus lite-node](../../../build/lotus/lotus-lite) (/home/runner/work/filecoin-docs/filecoin-docs/docs/get-started/lotus/installation.md:191:165)

Executes with --fix to fix automatically

Checking failed

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:links: `vuepress check-md docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:links script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-20T15_25_28_436Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:build: `npm run docs:links && vuepress build docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-20T15_25_28_454Z-debug.log
```
- No markdown files were changed, so no page checks were run!

**Comment by johndmulhausen** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```

> filecoin-docs@1.0.0 docs:build /home/runner/work/filecoin-docs/filecoin-docs
> npm run docs:links && vuepress build docs


> filecoin-docs@1.0.0 docs:links /home/runner/work/filecoin-docs/filecoin-docs
> vuepress check-md docs


Checking markdown...

1 dead links was found

  File is not found: [Lotus lite-node](../../../build/lotus/lotus-lite) (/home/runner/work/filecoin-docs/filecoin-docs/docs/get-started/lotus/installation.md:191:165)

Executes with --fix to fix automatically

Checking failed

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:links: `vuepress check-md docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:links script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-20T15_28_23_118Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:build: `npm run docs:links && vuepress build docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-20T15_28_23_139Z-debug.log
```
- No markdown files were changed, so no page checks were run!

**Comment by johndmulhausen** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```

> filecoin-docs@1.0.0 docs:build /home/runner/work/filecoin-docs/filecoin-docs
> npm run docs:links && vuepress build docs


> filecoin-docs@1.0.0 docs:links /home/runner/work/filecoin-docs/filecoin-docs
> vuepress check-md docs


Checking markdown...

1 dead links was found

  File is not found: [Lotus lite-node](../../../build/lotus/lotus-lite) (/home/runner/work/filecoin-docs/filecoin-docs/docs/get-started/lotus/installation.md:191:165)

Executes with --fix to fix automatically

Checking failed

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:links: `vuepress check-md docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:links script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-20T15_37_35_319Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:build: `npm run docs:links && vuepress build docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-20T15_37_35_333Z-debug.log
```
- No markdown files were changed, so no page checks were run!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful! Noting this in the PR comment.
<details><summary>Possible Grammar and Outbound Link Errors</summary>




</details>

**Comment by filecorgi** [comment]
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ciskip]` in this PR for details.
- Vuepress build was successful!
<details><summary>Possible Grammar and Outbound Link Errors</summary>




</details>

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful! Noting this in the PR comment.
- No markdown files were changed, so no page checks were run!

**Comment by filecorgi** [comment]
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ciskip]` in this PR for details.
- Vuepress build was successful!
<details><summary>Possible Grammar and Outbound Link Errors</summary>




</details>

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful! Noting this in the PR comment.
- No markdown files were changed, so no page checks were run!

**Comment by filecorgi** [comment]
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ciskip]` in this PR for details.
- Vuepress build was successful!
<details><summary>Possible Grammar and Outbound Link Errors</summary>




</details>

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful! Noting this in the PR comment.
- No markdown files were changed, so no page checks were run!

**Comment by filecorgi** [comment]
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ciskip]` in this PR for details.
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful! Noting this in the PR comment.
- No markdown files were changed, so no page checks were run!

**Comment by filecorgi** [comment]
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ciskip]` in this PR for details.
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful! Noting this in the PR comment.
- No markdown files were changed, so no page checks were run!

**Comment by filecorgi** [comment]
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ciskip]` in this PR for details.
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful! Noting this in the PR comment.
- No markdown files were changed, so no page checks were run!

**Comment by filecorgi** [comment]
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ciskip]` in this PR for details.
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/get-started/lotus/installation.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- The following link returned HTTP status code 405 (Method Not Allowed):
  https://golang.org/dl/
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/filecoin-docs/edit/master/docs/get-started/lotus/installation.md
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/filecoin-docs/issues/new?assignees=&labels=Content+Improvement&template=documentation-issue.md&title=%5BDOCS+ISSUE%5D+Page:+Lotus: install and setup
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/filecoin-docs/issues/new?assignees=&labels=Content+Improvement&template=content-request.md&title=%5BCONTENT+REQUEST%5D+%28add+your+title+here%21%29
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/filecoin-docs/issues/new?assignees=&labels=Content+Improvement&template=documentation-issue.md&title=%5BDOCS+ISSUE%5D+%28add+your+title+here%21%29
- Two consecutive dots
  ```
  ...tus applications and launch a Lotus Node.. This guide covers installing lotu...
                                             ^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ing Amazon Web Services, are covered in Running in the cloud. # Minimal requ...
                                             ^^^^^^^
  ```
- The verb “check out” can sound colloquial in this context. Consider using a more formal alternative.
  ```
  ...stributions you can run something like: Check out the official Golang instal...
                                             ^^^^^^^^^
  ```
- The verb “check out” can sound colloquial in this context. Consider using a more formal alternative.
  ```
  ...sponds to mainnet. If you are in China, check out the specific tips. Dependi...
                                             ^^^^^^^^^
  ```
- Possibly missing article found.
  ```
  ...bug that prevents Lotus from running on processor without adx instruction su...
                                             ^^^^^^^^^
  ```
- The operating system from Apple is written “macOS”.
  ```
  ...:  # Install Homebrew We recommend that MacOS users use Homebrew  (opens new...
                                             ^^^^^
  ```
- The verb “check out” can sound colloquial in this context. Consider using a more formal alternative.
  ```
  ...sponds to mainnet. If you are in China, check out the specific tips. Some ol...
                                             ^^^^^^^^^
  ```
- Possibly missing article found.
  ```
  ...bug that prevents Lotus from running on processor without adx instruction su...
                                             ^^^^^^^^^
  ```
- The verb ‘recommend’ is used with the gerund form.
  ```
  ... the background. When using mainnet, we recommend to start the daemon syncin...
                                             ^^^^^^^^^^^^^^^^^^
  ```
- The verb ‘set up’ is spelled as two words. The noun ‘setup’ is spelled as one.
  ```
  ...mand: During the first run, Lotus will: Setup its data folder at ~/.lotus. D...
                                             ^^^^^
  ```
- Consider a shorter alternative to avoid wordiness.
  ```
  ...lecoin network: # Stop the Lotus daemon In order to gracefully stop the runn...
                                             ^^^^^^^^^^^
  ```
### `docs/get-started/lotus/running-in-the-cloud.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io/
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/filecoin-docs/edit/master/docs/get-started/lotus/running-in-the-cloud.md
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/filecoin-docs/issues/new?assignees=&labels=Content+Improvement&template=documentation-issue.md&title=%5BDOCS+ISSUE%5D+Page:+Running in the cloud
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/filecoin-docs/issues/new?assignees=&labels=Content+Improvement&template=content-request.md&title=%5BCONTENT+REQUEST%5D+%28add+your+title+here%21%29
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/filecoin-docs/issues/new?assignees=&labels=Content+Improvement&template=documentation-issue.md&title=%5BDOCS+ISSUE%5D+%28add+your+title+here%21%29
- Use a smart opening quote here.
  ```
  ...e password you provided when creating a "Droplet" (virtual machine) with Lot...
                                             ^
  ```
- Use a smart closing quote here.
  ```
  ...rd you provided when creating a "Droplet" (virtual machine) with Lotus pre-i...
                                             ^
  ```
- Insert a space between the numerical value and the unit symbol.
  ```
  ...grammatically. For example, to create a 4GB filecoin-lotus Droplet in the SF...
                                             ^^^
  ```
- ‘on a regular basis’ might be wordy. Consider a shorter alternative.
  ```
  ...: # Amazon Web Services We publish AMIs on a regular basis for each of the f...
                                             ^^^^^^^^^^^^^^^^^^
  ```
- ‘root’ (underground organ of a plant) seems less likely than ‘route’ (an established line of travel).
  ```
  ...king. After about 20 minutes, the state root download will complete and lotu...
                                             ^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ctl will show the status of this job as Activating. (optional) Notice the th...
                                             ^^^^^^^^^^
  ```
- Two determiners in a row. Choose either “the” or “this”.
  ```
  ...is job as Activating. (optional) Notice the this job is not started yet. Don...
                                             ^^^^^^^^
  ```
### `docs/mine/lotus/miner-setup.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/filecoin-docs/edit/master/docs/mine/lotus/miner-setup.md
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/filecoin-docs/issues/new?assignees=&labels=Content+Improvement&template=documentation-issue.md&title=%5BDOCS+ISSUE%5D+Page:+Lotus Miner: setup a high performance miner
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/filecoin-docs/issues/new?assignees=&labels=Content+Improvement&template=content-request.md&title=%5BCONTENT+REQUEST%5D+%28add+your+title+here%21%29
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/filecoin-docs/issues/new?assignees=&labels=Content+Improvement&template=documentation-issue.md&title=%5BDOCS+ISSUE%5D+%28add+your+title+here%21%29
- The verb ‘set up’ is spelled as two words. The noun ‘setup’ is spelled as one.
  ```
  # Lotus Miner: setup a high performance miner This guide des...
                 ^^^^^
  ```
- If this is a compound adjective that modifies the following noun, use a hyphen.
  ```
  # Lotus Miner: setup a high performance miner This guide describes the necessar...
                         ^^^^^^^^^^^^^^^^
  ```
- Use a smart opening quote here.
  ```
  ...and make sure you have built Lotus with "Native Filecoin FFI". Once the inst...
                                             ^
  ```
- Use a smart closing quote here.
  ```
  ...ve built Lotus with "Native Filecoin FFI". Once the installation is complete...
                                             ^
  ```
- Insert a space between the numerical value and the unit symbol.
  ```
  ...ing the necessary swap If you have only 128GiB of RAM, you will need to make...
                                             ^^^^^^
  ```
- Insert a space between the numerical value and the unit symbol.
  ```
  ... your system provides at least an extra 256GiB of very fast swap (preferably...
                                             ^^^^^^
  ```
- It seems that a comma is missing.
  ```
  ...commend using separate owner and worker addresses though. Thus, create at le...
                                             ^^^^^^^^^^^^^^^^
  ```
- Insert a space between the numerical value and the unit symbol.
  ```
  ... of several files, which in the case of 32GiB sectors, total over 100GiB. We...
                                             ^^^^^
  ```
- Insert a space between the numerical value and the unit symbol.
  ```
  ...n the case of 32GiB sectors, total over 100GiB. We recommend setting a custo...
                                             ^^^^^^
  ```
- Consider using “all the”.
  ```
  ... # Checklist before launch To summarize all of the above, make sure that: Th...
                                             ^^^^^^^^^^
  ```
- It looks like you are using the wrong form of the noun or the verb. Did you mean “system has” or “systems have”?
  ```
  ... the cache folders specified above. The systems has enough swap and it is ac...
                                             ^^^^^^^^^^^
  ```
- ‘Miner’ seems less likely than ‘Minor’.
  ```
  ...ems has enough swap and it is active. # Miner initialization Before starting...
                                             ^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ...iner Before you start your miner, it is very important to configure it so th...
                                             ^^^^^^^^^^^^^^
  ```
- Use a comma after an introductory phrase.
  ```
  ... from any peer in the Filecoin network. For this you will need a stable publ...
                                             ^^^^^^^^
  ```
- ‘miner’ seems less likely than ‘minor’.
  ```
  ...ig.toml as follows: Once you start your miner, make sure you can connect to ...
                                             ^^^^^
  ```
- The verb ‘set up’ is spelled as two words. The noun ‘setup’ is spelled as one.
  ```
  ...ended tasks to be ready for prime-time: Setup your custom storage layout (re...
                                             ^^^^^
  ```
- Did you mean “to shut down”?
  ```
  ...uirements. Learn what is a right moment to shutdown/restart your miner Updat...
                                             ^^^^^^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/get-started/lotus/installation.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- The following link returned HTTP status code 405 (Method Not Allowed):
  https://golang.org/dl/
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ing Amazon Web Services, are covered in Running in the cloud. # Minimal requ...
                                             ^^^^^^^
  ```
- Use a smart opening quote here.
  ```
  ...ds to mainnet. If you are in China, see "Lotus: tips when running in China"....
                                             ^
  ```
- Use a smart closing quote here.
  ```
  ..., see "Lotus: tips when running in China". Depending on your CPU model, you ...
                                             ^
  ```
- A period is needed after the abbreviation ‘etc.’
  ```
  ...ge (configuration, chain data, wallets, etc). See advanced options for infor...
                                             ^^^
  ```
- Use a smart opening quote here.
  ```
  ...ds to mainnet. If you are in China, see "Lotus: tips when running in China"....
                                             ^
  ```
- Use a smart closing quote here.
  ```
  ..., see "Lotus: tips when running in China". Some older Intel and AMD processo...
                                             ^
  ```
### `docs/get-started/lotus/running-in-the-cloud.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- Use a smart opening quote here.
  ```
  ...e password you provided when creating a "Droplet" (virtual machine) with Lot...
                                             ^
  ```
- Use a smart closing quote here.
  ```
  ...rd you provided when creating a "Droplet" (virtual machine) with Lotus pre-i...
                                             ^
  ```
- ‘root’ (underground organ of a plant) seems less likely than ‘route’ (an established line of travel).
  ```
  ...king. After about 20 minutes, the state root download will complete and lotu...
                                             ^^^^
  ```
- Use a smart opening quote here.
  ```
  ...ctl will show the status of this job as "Activating". You will notice that t...
                                             ^
  ```
- Use a smart closing quote here.
  ```
  ...ow the status of this job as "Activating". You will notice that the job has ...
                                             ^
  ```
### `docs/mine/lotus/miner-setup.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- ‘miner’ seems less likely than ‘minor’.
  ```
  ... Lotus Miner: set up a high-performance miner This guide describes the neces...
                                             ^^^^^
  ```
- Use a smart opening quote here.
  ```
  ...and make sure you have built Lotus with "Native Filecoin FFI". Once the inst...
                                             ^
  ```
- Use a smart closing quote here.
  ```
  ...ve built Lotus with "Native Filecoin FFI". Once the installation is complete...
                                             ^
  ```
- ‘Miner’ seems less likely than ‘Minor’.
  ```
  ...tem has enough swap and it is active. # Miner initialization Before starting...
                                             ^^^^^
  ```
- ‘miner’ seems less likely than ‘minor’.
  ```
  ...ig.toml as follows: Once you start your miner, make sure you can connect to ...
                                             ^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/get-started/lotus/installation.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- The following link returned HTTP status code 405 (Method Not Allowed):
  https://golang.org/dl/
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ing Amazon Web Services, are covered in Running in the cloud. # Minimal requ...
                                             ^^^^^^^
  ```
- A period is needed after the abbreviation ‘etc.’
  ```
  ...ge (configuration, chain data, wallets, etc). See advanced options for infor...
                                             ^^^
  ```
### `docs/get-started/lotus/running-in-the-cloud.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- ‘root’ (underground organ of a plant) seems less likely than ‘route’ (an established line of travel).
  ```
  ...king. After about 20 minutes, the state root download will complete and lotu...
                                             ^^^^
  ```
### `docs/mine/lotus/miner-setup.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- ‘miner’ seems less likely than ‘minor’.
  ```
  ... Lotus Miner: set up a high-performance miner This guide describes the neces...
                                             ^^^^^
  ```
- ‘Miner’ seems less likely than ‘Minor’.
  ```
  ...tem has enough swap and it is active. # Miner initialization Before starting...
                                             ^^^^^
  ```
- ‘miner’ seems less likely than ‘minor’.
  ```
  ...ig.toml as follows: Once you start your miner, make sure you can connect to ...
                                             ^^^^^
  ```

**Pull request merged**
