### PR TITLE
feat: add multisig (safe) docs

### PR DESCRIPTION
**Pull request by xBalbinus**

### CODE REVIEW

**Review by smagdali — APPROVED** [review]
LGTM

**Comment by xBalbinus** [comment]
@smagdali could you merge? I don't have perms.

**Comment by longfeiWan9** [comment]
@xBalbinus there is a conflict, can you please resolve it first?

**Comment by xBalbinus** [comment]
Fixed

**Comment by xBalbinus** [comment]
@longfeiWan9 merge issue resolved, plz merge.

**Review by longfeiWan9 — APPROVED** [review]

**Pull request merged**
