### PR TITLE
Add a section that answers the "how to partner"-q

### PR DESCRIPTION
**Pull request by lksbrssr**
We frequently get this question. Here's an attempt to answer that we can then send people to.

### CODE REVIEW

**Comment by lksbrssr** [comment]
Please do not merge this; just a draft for now!

**Comment by johnnymatthews** [comment]
Converting this PR to draft mode. Ping if it's ready to merge @lksbrssr!

**Comment by johnnymatthews** [comment]
Are you still working on this PR @lksbrssr ?

**Comment by johnnymatthews** [comment]
Closing due to inactivity.

**Pull request closed without merging**
