### PR TITLE
Migration of Filecoin docs to Hugo w/DOKS theme

### LINKED ISSUE #1161: Remove VuePress and use the Doks package.
Documentation sites maintained by Protocol Labs are being migrated to use the [Doks](getdoks.org) Hugo site package.

## Tasks

- [x] Move content over to Doks theme.
- [x] Update font to Filecoin docs default.\
- [x] Fill out the homepage.
- [x] Left nav fix (no menus on subpages)
- [x] Right nav fix (no "On this page" navigation)
- [x] Figure out dead nav items (some areas are blank, like Software -- should we just pull it?)
- [x] Figure out what do to with section index content (it currently shows up as sub-item because tier 1 nav links do not load pages on click)
- [x] Convert `:::tip` instances to use `alert` shortcode
- [x] Migrate links to be Hugonic and use `relref`
- [x] Lotus logos abound in `/static` directory
- [x] Allow sections in topbar nav.
- [x] Enable search across site.
- [x] Create sidebar menus for each topbar section. (as seen here: https://github.com/atwriter/new_doks_site/pull/1/commits/40e6eae81a8748645525afadf21b1759ce5f2c77)
    - [x] About Filecoin
    - [x] Networks
    - [x] Get started
    - [x] Store
    - [x] Storage provider
    - [x] Build
    - [x] Reference
- [x] Remove `{{ $frontmatter.title }}` and `{{ $frontmatter.description }}`
- [x] Replicate the docs.filecoin.io homepage.
- [x] Order the sidebar to fit docs.filecoin.io
- [ ] Move images back into [page bundles](https://gohugo.io/content-management/page-bundles/)
- [ ] Topbar logo should use sans-serif font. No idea where this times-new-roman has come from...
- [ ] Topbar nav should highlight which section we're in.

### PR DESCRIPTION
**Pull request by johndmulhausen**
Implements URL-neutral migration (no redirects needed) by breaking out of the "/docs" box imposed by DOKS theme.

To browse live preview: 
https://deploy-preview-1144--filecoin-docs.netlify.app/

Closes #1161

### CODE REVIEW

**Comment by filecorgi** [comment]
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ciskip]` in this PR for details.
- Vuepress build failed...

```
npm ERR! Missing script: "docs:build"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-01-11T22_30_54_482Z-debug.log
```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```
npm ERR! Missing script: "docs:build"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-01-11T23_01_17_288Z-debug.log
```

**Comment by johnnymatthews** [comment]
Nice. I'm gonna switch this to draft for now while we're working on it.

Also, let's keep the existing font used in docs.filecoin.io:

```
font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif;
```

**Comment by johnnymatthews** [comment]
Gonna close this PR and make a new one with `ciskip` in the title. Filecorgi is getting in the way.

**Pull request closed without merging**
