### PR TITLE
Update miner configuration for hyperdrive

### PR DESCRIPTION
**Pull request by jennijuju**
Added sealing configuration docs, missing fee sections.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/mine/lotus/miner-configuration.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- Consider a shorter alternative to avoid wordiness.
  ```
  ...uration has all the items commented, so in order to customize one of the ite...
                                             ^^^^^^^^^^^
  ```
- It looks like there is a word missing here. Did you mean “listen to address”?
  ```
  ...tings of the miner API: As you see, the listen address is bound to the local...
                                             ^^^^^^^^^^^^^^
  ```
- Consider adding a comma after ‘Usually’ for more clarity.
  ```
  ...de would have to use to reach this API. Usually it is the miner's IP address...
                                             ^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ... noted in the setup instructions, it is very important to adjust this sectio...
                                             ^^^^^^^^^^^^^^
  ```
- A comma may be missing after the conjunctive/linking adverb ‘However’.
  ```
  ...ending the PublishStorageDeals message. However once MaxDealsPerPublishMsg a...
                                             ^^^^^^^
  ```
- After the expression ‘for example’ a comma is usually used.
  ```
  ... immediately publish all the deals. For example if PublishMsgPeriod is 1 hou...
                                             ^^^^^^^
  ```
- Do not use a colon (:) before a series that is introduced by a preposition (‘as’). Remove the colon or add a noun or a noun phrase after the preposition.
  ```
  ...completion its exit code is interpreted as: 0: success, proceed with the dea...
                                             ^^^
  ```
- Possibly missing article found.
  ```
  ...valFilter = "/bin/false". /bin/false is binary that immediately exits with a...
                                             ^^^^^^
  ```
- If this is a compound adjective that modifies the following noun, use a hyphen.
  ```
  ...art relatively soon. You can also use a third party content policy framework...
                                             ^^^^^^^^^^^
  ```
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...# Sealing section This section controls some of the behaviour around sector ...
                                             ^^^^^^^^^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...s hit: MaxPreCommitBatch is the maximum amount of sectors' pre-commitments t...
                                             ^^^^^^
  ```
- Possibly missing preposition found.
  ```
  ...et expires WILL cause the whole message fail. Therefore, we recommend miners...
                                             ^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...g queue, run: the output are the sector ids: To ignore the configuration and...
                                             ^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...k is hit: MaxCommitBatch is the maximum amount of sectors' prove-commitments...
                                             ^^^^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...ollateral MinCommitBatch is the minimum amount of sectors' prove-commitment ...
                                             ^^^^^^
  ```
- Use the singular noun “value” with the word ‘this’.
  ```
  ...te message. According to FIP-0013, this values cannot be less than 4, which ...
                                             ^^^^^^
  ```
- This noun is spelled as one word.
  ```
  ...ues cannot be less than 4, which is the cross over point where prove commit ...
                                             ^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably leave only “any of”.
  ```
  ...ut on single prove commit gas costs. If any of any of MaxCommitBatch, Commit...
                                             ^^^^^^^^^^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...g queue, run: the output are the sector ids: To ignore the configuration and...
                                             ^^^
  ```
- Did you mean “are”?
  ```
  ...tted is listed: If the sectors in queue is less than MinCommitBatch, then in...
                                             ^^
  ```
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...al seal workers, you may want to modify some of the options. # Fees section ...
                                             ^^^^^^^^^^^
  ```
- ‘fees’ seems less likely than ‘feed’.
  ```
  ...some of the options. # Fees section The fees section allows to set limits to...
                                             ^^^^
  ```
- Did you mean “setting”? Or maybe you should add a pronoun? In active voice, ‘allow’ + ‘to’ takes an object, usually a pronoun.
  ```
  ... # Fees section The fees section allows to set limits to the gas consumption...
                                             ^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ...se fee for the messages to be included. A very large max fee can however res...
                                             ^^^^^^^^^^^^
  ```
- Consider adding two commas here.
  ```
  ...es to be included. A very large max fee can however result in the quick burn...
                                             ^^^^^^^^^^^
  ```
- ‘then’ (next in order) seems less likely than ‘than’ (used in comparisons).
  ```
  ... necessary to have more funds available then any max fee set, even if the ac...
                                             ^^^^
  ```
- Comparison requires “than”, not ‘then’ nor ‘as’.
  ```
  ...even if the actual fee will be far less then the max fee set. *MaxWindowPost...
                                             ^^^^
  ```
- The abbreviation “e.g.” (= for example) requires two periods.
  ```
  ...setting used should remain fairly high, eg. 2FIL. # Addresses section The ad...
                                             ^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/mine/lotus/miner-configuration.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- Consider a shorter alternative to avoid wordiness.
  ```
  ...uration has all the items commented, so in order to customize one of the ite...
                                             ^^^^^^^^^^^
  ```
- It looks like there is a word missing here. Did you mean “listen to address”?
  ```
  ...tings of the miner API: As you see, the listen address is bound to the local...
                                             ^^^^^^^^^^^^^^
  ```
- Consider adding a comma after ‘Usually’ for more clarity.
  ```
  ...de would have to use to reach this API. Usually it is the miner's IP address...
                                             ^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ... noted in the setup instructions, it is very important to adjust this sectio...
                                             ^^^^^^^^^^^^^^
  ```
- A comma may be missing after the conjunctive/linking adverb ‘However’.
  ```
  ...ending the PublishStorageDeals message. However once MaxDealsPerPublishMsg a...
                                             ^^^^^^^
  ```
- After the expression ‘for example’ a comma is usually used.
  ```
  ... immediately publish all the deals. For example if PublishMsgPeriod is 1 hou...
                                             ^^^^^^^
  ```
- Do not use a colon (:) before a series that is introduced by a preposition (‘as’). Remove the colon or add a noun or a noun phrase after the preposition.
  ```
  ...completion its exit code is interpreted as: 0: success, proceed with the dea...
                                             ^^^
  ```
- Possibly missing article found.
  ```
  ...valFilter = "/bin/false". /bin/false is binary that immediately exits with a...
                                             ^^^^^^
  ```
- If this is a compound adjective that modifies the following noun, use a hyphen.
  ```
  ...art relatively soon. You can also use a third party content policy framework...
                                             ^^^^^^^^^^^
  ```
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...# Sealing section This section controls some of the behaviour around sector ...
                                             ^^^^^^^^^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...s hit: MaxPreCommitBatch is the maximum amount of sectors' pre-commitments t...
                                             ^^^^^^
  ```
- Possibly missing preposition found.
  ```
  ...et expires WILL cause the whole message fail. Therefore, we recommend miners...
                                             ^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...g queue, run: the output are the sector ids: To ignore the configuration and...
                                             ^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...k is hit: MaxCommitBatch is the maximum amount of sectors' prove-commitments...
                                             ^^^^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...ollateral MinCommitBatch is the minimum amount of sectors' prove-commitment ...
                                             ^^^^^^
  ```
- Use the singular noun “value” with the word ‘this’.
  ```
  ...te message. According to FIP-0013, this values cannot be less than 4, which ...
                                             ^^^^^^
  ```
- This noun is spelled as one word.
  ```
  ...ues cannot be less than 4, which is the cross over point where prove commit ...
                                             ^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably leave only “any of”.
  ```
  ...ut on single prove commit gas costs. If any of any of MaxCommitBatch, Commit...
                                             ^^^^^^^^^^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...g queue, run: the output are the sector ids: To ignore the configuration and...
                                             ^^^
  ```
- Did you mean “are”?
  ```
  ...tted is listed: If the sectors in queue is less than MinCommitBatch, then in...
                                             ^^
  ```
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...al seal workers, you may want to modify some of the options. # Fees section ...
                                             ^^^^^^^^^^^
  ```
- ‘fees’ seems less likely than ‘feed’.
  ```
  ...some of the options. # Fees section The fees section allows to set limits to...
                                             ^^^^
  ```
- Did you mean “setting”? Or maybe you should add a pronoun? In active voice, ‘allow’ + ‘to’ takes an object, usually a pronoun.
  ```
  ... # Fees section The fees section allows to set limits to the gas consumption...
                                             ^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ...se fee for the messages to be included. A very large max fee can however res...
                                             ^^^^^^^^^^^^
  ```
- Consider adding two commas here.
  ```
  ...es to be included. A very large max fee can however result in the quick burn...
                                             ^^^^^^^^^^^
  ```
- ‘then’ (next in order) seems less likely than ‘than’ (used in comparisons).
  ```
  ... necessary to have more funds available then any max fee set, even if the ac...
                                             ^^^^
  ```
- Comparison requires “than”, not ‘then’ nor ‘as’.
  ```
  ...even if the actual fee will be far less then the max fee set. *MaxWindowPost...
                                             ^^^^
  ```
- The abbreviation “e.g.” (= for example) requires two periods.
  ```
  ...setting used should remain fairly high, eg. 2FIL. # Addresses section The ad...
                                             ^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/mine/lotus/miner-configuration.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- Consider a shorter alternative to avoid wordiness.
  ```
  ...uration has all the items commented, so in order to customize one of the ite...
                                             ^^^^^^^^^^^
  ```
- It looks like there is a word missing here. Did you mean “listen to address”?
  ```
  ...tings of the miner API: As you see, the listen address is bound to the local...
                                             ^^^^^^^^^^^^^^
  ```
- Consider adding a comma after ‘Usually’ for more clarity.
  ```
  ...de would have to use to reach this API. Usually it is the miner's IP address...
                                             ^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ... noted in the setup instructions, it is very important to adjust this sectio...
                                             ^^^^^^^^^^^^^^
  ```
- A comma may be missing after the conjunctive/linking adverb ‘However’.
  ```
  ...ending the PublishStorageDeals message. However once MaxDealsPerPublishMsg a...
                                             ^^^^^^^
  ```
- After the expression ‘for example’ a comma is usually used.
  ```
  ... immediately publish all the deals. For example if PublishMsgPeriod is 1 hou...
                                             ^^^^^^^
  ```
- Do not use a colon (:) before a series that is introduced by a preposition (‘as’). Remove the colon or add a noun or a noun phrase after the preposition.
  ```
  ...completion its exit code is interpreted as: 0: success, proceed with the dea...
                                             ^^^
  ```
- Possibly missing article found.
  ```
  ...valFilter = "/bin/false". /bin/false is binary that immediately exits with a...
                                             ^^^^^^
  ```
- If this is a compound adjective that modifies the following noun, use a hyphen.
  ```
  ...art relatively soon. You can also use a third party content policy framework...
                                             ^^^^^^^^^^^
  ```
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...# Sealing section This section controls some of the behaviour around sector ...
                                             ^^^^^^^^^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...s hit: MaxPreCommitBatch is the maximum amount of sectors' pre-commitments t...
                                             ^^^^^^
  ```
- Possibly missing preposition found.
  ```
  ...et expires WILL cause the whole message fail. Therefore, we recommend miners...
                                             ^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...g queue, run: the output are the sector ids: To ignore the configuration and...
                                             ^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...k is hit: MaxCommitBatch is the maximum amount of sectors' prove-commitments...
                                             ^^^^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...ollateral MinCommitBatch is the minimum amount of sectors' prove-commitment ...
                                             ^^^^^^
  ```
- Use the singular noun “value” with the word ‘this’.
  ```
  ...te message. According to FIP-0013, this values cannot be less than 4, which ...
                                             ^^^^^^
  ```
- This noun is spelled as one word.
  ```
  ...ues cannot be less than 4, which is the cross over point where prove commit ...
                                             ^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably leave only “any of”.
  ```
  ...ut on single prove commit gas costs. If any of any of MaxCommitBatch, Commit...
                                             ^^^^^^^^^^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...g queue, run: the output are the sector ids: To ignore the configuration and...
                                             ^^^
  ```
- Did you mean “are”?
  ```
  ...tted is listed: If the sectors in queue is less than MinCommitBatch, then in...
                                             ^^
  ```
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...al seal workers, you may want to modify some of the options. # Fees section ...
                                             ^^^^^^^^^^^
  ```
- ‘fees’ seems less likely than ‘feed’.
  ```
  ...some of the options. # Fees section The fees section allows to set limits to...
                                             ^^^^
  ```
- Did you mean “setting”? Or maybe you should add a pronoun? In active voice, ‘allow’ + ‘to’ takes an object, usually a pronoun.
  ```
  ... # Fees section The fees section allows to set limits to the gas consumption...
                                             ^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ...se fee for the messages to be included. A very large max fee can however res...
                                             ^^^^^^^^^^^^
  ```
- Consider adding two commas here.
  ```
  ...es to be included. A very large max fee can however result in the quick burn...
                                             ^^^^^^^^^^^
  ```
- ‘then’ (next in order) seems less likely than ‘than’ (used in comparisons).
  ```
  ... necessary to have more funds available then any max fee set, even if the ac...
                                             ^^^^
  ```
- Comparison requires “than”, not ‘then’ nor ‘as’.
  ```
  ...even if the actual fee will be far less then the max fee set. *MaxWindowPost...
                                             ^^^^
  ```
- The abbreviation “e.g.” (= for example) requires two periods.
  ```
  ...setting used should remain fairly high, eg. 2FIL. # Addresses section The ad...
                                             ^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/mine/lotus/miner-configuration.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- Consider a shorter alternative to avoid wordiness.
  ```
  ...uration has all the items commented, so in order to customize one of the ite...
                                             ^^^^^^^^^^^
  ```
- It looks like there is a word missing here. Did you mean “listen to address”?
  ```
  ...tings of the miner API: As you see, the listen address is bound to the local...
                                             ^^^^^^^^^^^^^^
  ```
- Consider adding a comma after ‘Usually’ for more clarity.
  ```
  ...de would have to use to reach this API. Usually it is the miner's IP address...
                                             ^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ... noted in the setup instructions, it is very important to adjust this sectio...
                                             ^^^^^^^^^^^^^^
  ```
- A comma may be missing after the conjunctive/linking adverb ‘However’.
  ```
  ...ending the PublishStorageDeals message. However once MaxDealsPerPublishMsg a...
                                             ^^^^^^^
  ```
- After the expression ‘for example’ a comma is usually used.
  ```
  ... immediately publish all the deals. For example if PublishMsgPeriod is 1 hou...
                                             ^^^^^^^
  ```
- Do not use a colon (:) before a series that is introduced by a preposition (‘as’). Remove the colon or add a noun or a noun phrase after the preposition.
  ```
  ...completion its exit code is interpreted as: 0: success, proceed with the dea...
                                             ^^^
  ```
- Possibly missing article found.
  ```
  ...valFilter = "/bin/false". /bin/false is binary that immediately exits with a...
                                             ^^^^^^
  ```
- If this is a compound adjective that modifies the following noun, use a hyphen.
  ```
  ...art relatively soon. You can also use a third party content policy framework...
                                             ^^^^^^^^^^^
  ```
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...# Sealing section This section controls some of the behaviour around sector ...
                                             ^^^^^^^^^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...s hit: MaxPreCommitBatch is the maximum amount of sectors' pre-commitments t...
                                             ^^^^^^
  ```
- Possibly missing preposition found.
  ```
  ...et expires WILL cause the whole message fail. Therefore, we recommend miners...
                                             ^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...g queue, run: the output are the sector ids: To ignore the configuration and...
                                             ^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...k is hit: MaxCommitBatch is the maximum amount of sectors' prove-commitments...
                                             ^^^^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...ollateral MinCommitBatch is the minimum amount of sectors' prove-commitment ...
                                             ^^^^^^
  ```
- Use the singular noun “value” with the word ‘this’.
  ```
  ...te message. According to FIP-0013, this values cannot be less than 4, which ...
                                             ^^^^^^
  ```
- This noun is spelled as one word.
  ```
  ...ues cannot be less than 4, which is the cross over point where prove commit ...
                                             ^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably leave only “any of”.
  ```
  ...ut on single prove commit gas costs. If any of any of MaxCommitBatch, Commit...
                                             ^^^^^^^^^^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...g queue, run: the output are the sector ids: To ignore the configuration and...
                                             ^^^
  ```
- Did you mean “are”?
  ```
  ...tted is listed: If the sectors in queue is less than MinCommitBatch, then in...
                                             ^^
  ```
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...al seal workers, you may want to modify some of the options. # Fees section ...
                                             ^^^^^^^^^^^
  ```
- ‘fees’ seems less likely than ‘feed’.
  ```
  ...some of the options. # Fees section The fees section allows to set limits to...
                                             ^^^^
  ```
- Did you mean “setting”? Or maybe you should add a pronoun? In active voice, ‘allow’ + ‘to’ takes an object, usually a pronoun.
  ```
  ... # Fees section The fees section allows to set limits to the gas consumption...
                                             ^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ...se fee for the messages to be included. A very large max fee can however res...
                                             ^^^^^^^^^^^^
  ```
- Consider adding two commas here.
  ```
  ...es to be included. A very large max fee can however result in the quick burn...
                                             ^^^^^^^^^^^
  ```
- ‘then’ (next in order) seems less likely than ‘than’ (used in comparisons).
  ```
  ... necessary to have more funds available then any max fee set, even if the ac...
                                             ^^^^
  ```
- Comparison requires “than”, not ‘then’ nor ‘as’.
  ```
  ...even if the actual fee will be far less then the max fee set. *MaxWindowPost...
                                             ^^^^
  ```
- The abbreviation “e.g.” (= for example) requires two periods.
  ```
  ...setting used should remain fairly high, eg. 2FIL. # Addresses section The ad...
                                             ^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/mine/lotus/miner-configuration.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- Consider a shorter alternative to avoid wordiness.
  ```
  ...uration has all the items commented, so in order to customize one of the ite...
                                             ^^^^^^^^^^^
  ```
- It looks like there is a word missing here. Did you mean “listen to address”?
  ```
  ...tings of the miner API: As you see, the listen address is bound to the local...
                                             ^^^^^^^^^^^^^^
  ```
- Consider adding a comma after ‘Usually’ for more clarity.
  ```
  ...de would have to use to reach this API. Usually it is the miner's IP address...
                                             ^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ... noted in the setup instructions, it is very important to adjust this sectio...
                                             ^^^^^^^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...y benchmarking or by pledging a sector. WARNING The final value of ExpectedS...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...soon. # Publishing several deals in one message The PublishStorageDeals mess...
                                             ^^^^^^^
  ```
- A comma may be missing after the conjunctive/linking adverb ‘However’.
  ```
  ...ending the PublishStorageDeals message. However once MaxDealsPerPublishMsg a...
                                             ^^^^^^^
  ```
- After the expression ‘for example’ a comma is usually used.
  ```
  ... immediately publish all the deals. For example if PublishMsgPeriod is 1 hou...
                                             ^^^^^^^
  ```
- Do not use a colon (:) before a series that is introduced by a preposition (‘as’). Remove the colon or add a noun or a noun phrase after the preposition.
  ```
  ...completion its exit code is interpreted as: 0: success, proceed with the dea...
                                             ^^^
  ```
- Possibly missing article found.
  ```
  ...valFilter = "/bin/false". /bin/false is binary that immediately exits with a...
                                             ^^^^^^
  ```
- If this is a compound adjective that modifies the following noun, use a hyphen.
  ```
  ...art relatively soon. You can also use a third party content policy framework...
                                             ^^^^^^^^^^^
  ```
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...# Sealing section This section controls some of the behaviour around sector ...
                                             ^^^^^^^^^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...s hit: MaxPreCommitBatch is the maximum amount of sectors' pre-commitments t...
                                             ^^^^^^
  ```
- Possibly missing preposition found.
  ```
  ...et expires WILL cause the whole message fail. Therefore, we recommend miners...
                                             ^^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...tions. MinPreCommitBatch is the minimum amount of sectors' pre-commitment to...
                                             ^^^^^^
  ```
- The word “therefore” is an adverb that can’t be used like a conjunction, and therefore needs to be separated from the sentence.
  ```
  ...orsBatch cost less gas than sending via PreCommitSector, therefore, we recom...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- The verb ‘recommend’ is used with the gerund form.
  ```
  ...ding via PreCommitSector, therefore, we recommend to keep this value as 1. N...
                                             ^^^^^^^^^^^^^^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...g queue, run: the output are the sector ids: To ignore the configuration and...
                                             ^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...k is hit: MaxCommitBatch is the maximum amount of sectors' prove-commitments...
                                             ^^^^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...ollateral MinCommitBatch is the minimum amount of sectors' prove-commitment ...
                                             ^^^^^^
  ```
- Use the singular noun “value” with the word ‘this’.
  ```
  ...te message. According to FIP-0013, this values cannot be less than 4, which ...
                                             ^^^^^^
  ```
- This noun is spelled as one word.
  ```
  ...ues cannot be less than 4, which is the cross over point where prove commit ...
                                             ^^^^^^^^^^
  ```
- This phrase is duplicated. You should probably leave only “any of”.
  ```
  ...ut on single prove commit gas costs. If any of any of MaxCommitBatch, Commit...
                                             ^^^^^^^^^^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...g queue, run: the output are the sector ids: To ignore the configuration and...
                                             ^^^
  ```
- Did you mean “are”?
  ```
  ...tted is listed: If the sectors in queue is less than MinCommitBatch, then in...
                                             ^^
  ```
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...al seal workers, you may want to modify some of the options. # Fees section ...
                                             ^^^^^^^^^^^
  ```
- ‘fees’ seems less likely than ‘feed’.
  ```
  ...some of the options. # Fees section The fees section allows to set limits to...
                                             ^^^^
  ```
- Did you mean “setting”? Or maybe you should add a pronoun? In active voice, ‘allow’ + ‘to’ takes an object, usually a pronoun.
  ```
  ... # Fees section The fees section allows to set limits to the gas consumption...
                                             ^^^^^^
  ```
- Possibly missing comma found.
  ```
  ... by the miner: Depending on the network congestion the base fee for a transa...
                                             ^^^^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ...se fee for the messages to be included. A very large max fee can however res...
                                             ^^^^^^^^^^^^
  ```
- Consider adding two commas here.
  ```
  ...es to be included. A very large max fee can however result in the quick burn...
                                             ^^^^^^^^^^^
  ```
- ‘then’ (next in order) seems less likely than ‘than’ (used in comparisons).
  ```
  ... necessary to have more funds available then any max fee set, even if the ac...
                                             ^^^^
  ```
- Comparison requires “than”, not ‘then’ nor ‘as’.
  ```
  ...even if the actual fee will be far less then the max fee set. *MaxWindowPost...
                                             ^^^^
  ```
- The abbreviation “e.g.” (= for example) requires two periods.
  ```
  ...setting used should remain fairly high, eg. 2FIL. # Addresses section The ad...
                                             ^^^
  ```
- Possibly missing comma found.
  ```
  ...es when network fees are high. For more details see the Miner addresses sect...
                                             ^^^^^^^
  ```

**Review by johnnymatthews — APPROVED** [review]
Made some minor changes, but the content looks OK. Merge when ready!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/mine/lotus/miner-configuration.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- It looks like there is a word missing here. Did you mean “listen to address”?
  ```
  ...tings of the miner API: As you see, the listen address is bound to the local...
                                             ^^^^^^^^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ... noted in the setup instructions, it is very important to adjust this sectio...
                                             ^^^^^^^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...y benchmarking or by pledging a sector. WARNING The final value of ExpectedS...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...soon. # Publishing several deals in one message The PublishStorageDeals mess...
                                             ^^^^^^^
  ```
- Do not use a colon (:) before a series that is introduced by a preposition (‘as’). Remove the colon or add a noun or a noun phrase after the preposition.
  ```
  ...ompletion, its exit code is interpreted as: 0: success, proceed with the dea...
                                             ^^^
  ```
- Possibly missing article found.
  ```
  ...valFilter = "/bin/false". /bin/false is binary that immediately exits with a...
                                             ^^^^^^
  ```
- If this is a compound adjective that modifies the following noun, use a hyphen.
  ```
  ...art relatively soon. You can also use a third party content policy framework...
                                             ^^^^^^^^^^^
  ```
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...# Sealing section This section controls some of the behavior around sector s...
                                             ^^^^^^^^^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...s hit: MaxPreCommitBatch is the maximum amount of sectors' pre-commitments t...
                                             ^^^^^^
  ```
- Possibly missing preposition found.
  ```
  ...et expires WILL cause the whole message fail. Therefore, we recommend miners...
                                             ^^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...tions. MinPreCommitBatch is the minimum amount of sectors' pre-commitment to...
                                             ^^^^^^
  ```
- The word “therefore” is an adverb that can’t be used like a conjunction, and therefore needs to be separated from the sentence.
  ```
  ...orsBatch cost less gas than sending via PreCommitSector, therefore, we recom...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- The verb ‘recommend’ is used with the gerund form.
  ```
  ...ding via PreCommitSector, therefore, we recommend to keep this value as 1. N...
                                             ^^^^^^^^^^^^^^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...ng queue, run: the output is the sector ids: To ignore the configuration and...
                                             ^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...k is hit: MaxCommitBatch is the maximum amount of sectors' prove-commitments...
                                             ^^^^^^
  ```
- ‘Amount of’ should usually only be used with uncountable or mass nouns. Consider using “number” if this is not the case.
  ```
  ...ollateral MinCommitBatch is the minimum amount of sectors' prove-commitment ...
                                             ^^^^^^
  ```
- This abbreviation for “identification” is spelled all-uppercase.
  ```
  ...ng queue, run: the output is the sector ids: To ignore the configuration and...
                                             ^^^
  ```
- If the text is a generality, ‘of the’ is not necessary.
  ```
  ...al seal workers, you may want to modify some of the options. # Fees section ...
                                             ^^^^^^^^^^^
  ```
- ‘fees’ seems less likely than ‘feed’.
  ```
  ...some of the options. # Fees section The fees section allows to set limits to...
                                             ^^^^
  ```
- Did you mean “setting”? Or maybe you should add a pronoun? In active voice, ‘allow’ + ‘to’ takes an object, usually a pronoun.
  ```
  ... # Fees section The fees section allows to set limits to the gas consumption...
                                             ^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ...se fee for the messages to be included. A very large max fee can, however, r...
                                             ^^^^^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...es when network fees are high. For more details see the Miner addresses sect...
                                             ^^^^^^^
  ```

**Pull request merged**
