### PR TITLE
Creates metamask setup. Moves FilForwarder.

### PR DESCRIPTION
**Pull request by johnnymatthews**
Closes https://github.com/filecoin-project/filecoin-docs/issues/1874

This PR:

- Removes unnecessary Wallet mentions from /reference/general/overview/
- Moves _Add to MetaMask_ pages in the Networks section over to a new `/basics/assets/metamask-setup` page
    - Includes codetabs to separate each network.
    - Looks nice and tidy.
 - Changes the `/smart-contracts/wallets` topbar menu item to point to `/basics/assets/metamask-setup`.
    - This might not be necessary, but I threw it in here just in-case users are expecting to see the Wallet link in that dropdown.
- Renames FilForwarder and moves it to `/smart-contracts/filecoin-evm-runtime/actor-types/`.
- Removes the `/smart-contracts/wallet` sidebar menu section.

This PR looks a bit intimating because it's moved a few files, which is why GitHub is showing 43 changes files. But there's been very little actual content changes.

### CODE REVIEW

**Comment by mishmosh** [comment]
> Removes unnecessary Wallet mentions from /reference/general/overview/
👍

> Moves Add to MetaMask pages in the Networks section over to a new /basics/assets/metamask-setup page
> Includes codetabs to separate each network.
> Looks nice and tidy.
This looks great! The codetabs are a nice pattern.

> Changes the /smart-contracts/wallets topbar menu item to point to /basics/assets/metamask-setup.
> This might not be necessary, but I threw it in here just in-case users are expecting to see the Wallet link in that dropdown.
I think we should remove this, and just link to Wallets details from within any pages/sections as-needed. Navigation menus set users up to expect a hierarchy, so it's disorienting to break that pattern.

> Renames FilForwarder and moves it to /smart-contracts/filecoin-evm-runtime/actor-types/.
There's an argument to be made for moving all of ethereum-address-compatibility/ to the "Wallets" section because it's user-facing (whereas Smart Contracts section is developer-facing), but we can revisit in a later issue/PR.

> Removes the /smart-contracts/wallet sidebar menu section.
👍

**Review by mishmosh — COMMENTED** [review]
> Removes unnecessary Wallet mentions from /reference/general/overview/

👍

> Moves Add to MetaMask pages in the Networks section over to a new /basics/assets/metamask-setup page
> Includes codetabs to separate each network.
> Looks nice and tidy.

This looks great! The codetabs are a nice pattern.

> Changes the /smart-contracts/wallets topbar menu item to point to /basics/assets/metamask-setup.
> This might not be necessary, but I threw it in here just in-case users are expecting to see the Wallet link in that dropdown.

I think we should remove this, and just link to Wallets details from within any pages/sections as-needed. Navigation menus set users up to expect a hierarchy, so it's disorienting to break that pattern.

> Renames FilForwarder and moves it to /smart-contracts/filecoin-evm-runtime/actor-types/.

There's an argument to be made for moving all of the FilForwarder section to the "Wallets" section because it's user-facing (whereas Smart Contracts section is developer-facing), but we can revisit in a later issue/PR.

> Removes the /smart-contracts/wallet sidebar menu section.

👍

**Comment by johnnymatthews** [comment]
> There's an argument to be made for moving all of the FilForwarder section to the "Wallets" section because it's user-facing (whereas Smart Contracts section is developer-facing), but we can revisit in a later issue/PR. -- @mishmosh 

I mostly agree, the Glif / GUI interface for FilForwarder is pretty general, and should be included in the `/basics/assets/transfer-fil` page. But the contract explanation part of that page is pretty smart-contract-developer specific. I'll make a new issue to track this discussion though, so we can get this merged.

**Review by mishmosh — APPROVED** [review]
lgtm!

**Pull request merged**
