### PR TITLE
Add steps for installing Lotus using AppImages.

### PR DESCRIPTION
**Pull request by coryschwartz**
These are pretty new!

Watch to make sure https://snapcraft.io/lotus-filecoin looks right and https://github.com/filecoin-project/lotus/pull/6388 is merged before adding this to the docs.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/get-started/lotus/installation.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- The following link returned HTTP status code 405 (Method Not Allowed):
  https://golang.org/dl/
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ing Amazon Web Services, are covered in Running in the cloud. # Minimal requ...
                                             ^^^^^^^
  ```
- A period is needed after the abbreviation ‘etc.’
  ```
  ...ge (configuration, chain data, wallets, etc). See advanced options for infor...
                                             ^^^
  ```
- Possibly missing comma found.
  ```
  ...n. # Native Filecoin FFI Some newer CPU architectures like AMD's Zen and Int...
                                             ^^^^^^^^^^^^^
  ```
- The operating system from Apple is written “macOS”.
  ```
  ...ific to macOS. You can install Lotus on MacOS 10.11 (El Capitan, 2015) or hi...
                                             ^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/get-started/lotus/installation.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- The following link returned HTTP status code 405 (Method Not Allowed):
  https://golang.org/dl/
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ing Amazon Web Services, are covered in Running in the cloud. # Minimal requ...
                                             ^^^^^^^
  ```
- A period is needed after the abbreviation ‘etc.’
  ```
  ...ge (configuration, chain data, wallets, etc). See advanced options for infor...
                                             ^^^
  ```
- Possibly missing comma found.
  ```
  ...n. # Native Filecoin FFI Some newer CPU architectures like AMD's Zen and Int...
                                             ^^^^^^^^^^^^^
  ```
- The operating system from Apple is written “macOS”.
  ```
  ...ific to macOS. You can install Lotus on MacOS 10.11 (El Capitan, 2015) or hi...
                                             ^^^^^
  ```

**Comment by johnnymatthews** [comment]
Oh perfect! Thanks for starting this PR. I'm gonna turn it into a draft, because there's a couple more things I want to tweak before this gets merged.

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/get-started/lotus/installation.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/lotus/releases/latest
- The following link returned HTTP status code 405 (Method Not Allowed):
  https://golang.org/dl/
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ing Amazon Web Services, are covered in Running in the cloud. # Minimal requ...
                                             ^^^^^^^
  ```
- A period is needed after the abbreviation ‘etc.’
  ```
  ...ge (configuration, chain data, wallets, etc). See advanced options for infor...
                                             ^^^
  ```
- Possibly missing comma found.
  ```
  ...n. # Native Filecoin FFI Some newer CPU architectures like AMD's Zen and Int...
                                             ^^^^^^^^^^^^^
  ```
- The operating system from Apple is written “macOS”.
  ```
  ...ific to macOS. You can install Lotus on MacOS 10.11 (El Capitan, 2015) or hi...
                                             ^^^^^
  ```

**Comment by johnnymatthews** [comment]
Closes #892

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/get-started/lotus/installation.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- The following link returned HTTP status code 302 (Found):
  https://github.com/filecoin-project/lotus/releases/latest
- The following link returned HTTP status code 405 (Method Not Allowed):
  https://golang.org/dl/
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ing Amazon Web Services, are covered in Running in the cloud. # Minimal requ...
                                             ^^^^^^^
  ```
- Possibly missing comma found.
  ```
  .... # Minimal requirements To run a Lotus node your computer must have: macOS ...
                                             ^^^^
  ```
- Possibly missing comma found.
  ```
  ...cal/go/bin to your path. For most Linux distributions you can run something ...
                                             ^^^^^^^^^^^^^
  ```
- A period is needed after the abbreviation ‘etc.’
  ```
  ...ge (configuration, chain data, wallets, etc). See advanced options for infor...
                                             ^^^
  ```
- Possibly missing comma found.
  ```
  ...n. # Native Filecoin FFI Some newer CPU architectures like AMD's Zen and Int...
                                             ^^^^^^^^^^^^^
  ```
- The operating system from Apple is written “macOS”.
  ```
  ...ific to macOS. You can install Lotus on MacOS 10.11 (El Capitan, 2015) or hi...
                                             ^^^^^
  ```

**Pull request merged**
