### PR TITLE
update color scheme

### PR DESCRIPTION
**Pull request by terichadbourne**

### CODE REVIEW

**Comment by terichadbourne** [comment]
@mishmosh I've changed the accent color that fuels the links, the bar next to the part of the left nav that you're on, etc. to match the current Filecoin docs site. (The color I found there is actually not any of the ones from the Filecoin brand book, so I've pasted screenshots of two alternatives from the brand book below.) What looks good? Do you see other colors that you'd like changed? 

BEFORE: 
image
image

AFTER (#00AAAC) - in this PR:
image
image

ALTERNATIVE 1 (logo color: #00D2D6)
image
image


ALTERNATIVE 2: (darkest supplemental teal from brand book: #026863)
image
image

**Comment by mishmosh** [comment]
Thanks @terichadbourne, looking good. Personally I prefer After (#00AAAC) or Alternative 2. Can you run the text/background color combos through an accessibility checker such as https://webaim.org/resources/contrastchecker/? If After passes with an AA score for normal text, let's ship this PR as you've written.

I am expecting an updated brand book at end of March (from another workstream), so let's pick something accessible + nice from these current options, and update later if needed.

**Comment by terichadbourne** [comment]
Thanks for pointing me to that tool, @mishmosh.  Both of your top two picks fail all of those tests (After is less bad than Alternative 1). The original from the IPFS site only passes large AA. Alternative 2 passes everything except for normal AAA on each of the three background colors it's seen on above. Okay with me switching to Alternative 2 for now and re-assessing when we have the new brand book?

**Comment by mishmosh** [comment]
> Okay with me switching to Alternative 2 for now and re-assessing when we have the new brand book?

Yes, sounds like a plan.

**Pull request merged**
