### PR TITLE
New layout and simplified organization of site

### PR DESCRIPTION
**Pull request by duncan64**
[**Rendered main page**](https://deploy-preview-26--filecoin-docs.netlify.com/)

In this pull request the main page is empty, waiting for individual pages to be merged in. I’ve also removed the placeholder pages, but these can be added back in if we want to.

### CODE REVIEW

**Comment by terichadbourne** [comment]
@duncan64 I don't feel I can proof this because you've removed all content, including the content that was complete. There's nothing to click on to display or explore the nav and see whether I agree with your layout choices. Could you please put at least the completed content back so we can have a chance to explore your layout suggestion? If it's not clear to you which content was complete, I'm happy to get on a call with you and walk through it.

FWIW the placeholders were there so that people could see how the nav would work - where there were second layers in the nav, where L2 headers created nav, etc. My personal preference would be to put the placeholders back as well so that we can all agree on the chunking of content and what topics are needed but not yet drafted. @mishmosh can make the call on this.

**Comment by duncan64** [comment]
Ah yes, I see how this is hard to review without the placeholder content.

The reason I removed the nav links was so that this pull request merges cleanly regardless of whether it is merged before or after my other pull requests.

In the meantime, I have attached screenshots showing what the homepage and content pages look like with all the links back in:

docs-home-page

docs-example-page

**Comment by mishmosh** [comment]
> so that this pull request merges cleanly regardless
Currently this would overwrite the existing navigation (leaving `master` with a blank left nav) and not merge cleanly after all.

Please separate into 2 PRs:

**Replace front page design**
This looks beautiful and we will merge as soon as it's deployable to master. In addition to the updates to README.md, it also needs:
- Content links added to each block, as in mockup.
- "Reference" is empty right now and "Project" is very slim. Can we use 4 major blocks: "Introduction", "Getting Started" or "How-to" (merge them and pick your preferred name), "Community", "Project". Or keep "Reference" (so 5 sections) and add Specification link there, with the idea to add API specs, etc. in the future.
- Unwind the changes to config.js so that the left nav isn't empty.

**Update left navbar**
- Since this would make it harder for us to pull in IPFS's framework updates I'm more reluctant to make this change.

**Comment by duncan64** [comment]
I would like to separate this into two pull requests, but for now this is blocked due to JS changes needed to make the front page work.

In order for the front page to receive the list of pages to display, `Layout.vue` needs to be modified as I’ve done in this pull request. Unfortunately this pulls in a lot of JS along with it. There might be another way to get the list of pages but I haven’t found a clean way of doing it yet.

I’m parking this pull request until I can investigate it further.

**Pull request closed without merging**
