### PR TITLE
Issue #1759 - Add/deal making explainer

### PR DESCRIPTION
**Pull request by trruckerfling**
## Programmatic Storage Deal Making

Filecoin’s base storage deal making method, prior to the introduction of the Filecoin Virtual Machine (FVM), requires the Client who wants to store the data, to run a node, find a Storage Provider and complete the storage deal. You can read more about the workflow [here](https://lotus.filecoin.io/tutorials/lotus/store-and-retrieve/store-data/). 

FVM brings programmability to storage deal making on Filecoin, automating the process for scalability and enabling dApp development to integrate the important task of storing data into various workflows.

With the Filecoin EVM (FEVM), an Ethereum-compatible version of FVM, launching to mainnet before the FVM Native version, the existing primitive to programmatic storage deal making utilizes the EVM smart contract to represent the Client. 

Currently, there are two methods to programmatic storage deal making, with FEVM:

### Client Contract (tutorial here)

The client contract allows a Filecoin EVM smart contract to be the Client and it participates in the deal making flow end-to-end. 

The client contract interacts with Storage Providers and generates deals on behalf of a Client, entirely on-chain. It emits a deal proposal for Storage Providers to pick up and activate a storage deal for. The client contract then helps authenticate that the published storage deal is aligned with the Client’s initial deal proposal. 

Data preparation is also required, before initiating the deal proposal from the client contract and this preparation outputs several pieces of information that is required for the deal proposal - [CAR file](https://spec.filecoin.io/systems/filecoin_files/piece/#:~:text=A%20CAR%20file%20is%20an,provider%20as%20we%20discuss%20later.) link, CAR file size, data file size and [data CID](https://spec.filecoin.io/systems/filecoin_files/piece/). There are both manual and tooling options to achieve this, which will be shown in the client contract tutorial. 

It is important to note, at time of writing, that the client contract only works with Storage Providers running the latest [Boost](https://boost.filecoin.io/) release [v1.6.0](https://github.com/filecoin-project/boost/releases/tag/v1.6.0) and who have enabled the feature to take FVM deals. Such Storage Providers will be listening on-chain, to look out for client contract deal proposals events to accept. If the Client wants to select a specific Storage Provider, they will need to be running that latest release.

### Deal Bounty Contract (tutorial here)

The deal bounty contract represents the proposal from the Client but does not manage the deal making. Instead, it incentivizes a third party “bounty hunter” to pass the deal proposal to the Storage Provider and secure the deal.

The deal bounty contract consists of a list of data CIDs that the “bounty hunter” will pick up to make the deal and return the deal ID, in order to receive the bounty in the deal bounty escrow. 

The contract will check with the [Filecoin built-in storage market actor](https://docs.filecoin.io/developers/reference/built-in-actors/storage-market-actor/), to confirm whether the supplied deal ID is activated and stores the claimed data. Once validated, the deal bounty contract will pay the bounty hunter out.

As with the client contract, data has to be prepared in order to add the data CID to the contract.

### Extension Ideas

With programmatic storage building blocks, here are some examples of what you can build: 
- [DataDAOs](https://rfs.fvm.dev/#482335d5b27543b3b0d5e81b995b719d) can implement a main client contract that adds piece CIDs to store new data, through a voting mechanism
- [Perpetual storage](https://rfs.fvm.dev/#2934f09e0d8c4280a6d9a5c08ffdeee1) can be achieved with client contracts that recycle piece CIDs from expiring deals into their authorization sets
For more use case ideas with FVM, see the [Request for Startups](https://rfs.fvm.dev/).

### Improve the acceptance rate of your deal proposal

Storage Providers are better incentivized to accept deal proposals that meet certain parameters (e.g. deal size, [FIL+ datacap verified](https://filplus.info/) like a KYC). If your deal proposal is not well aligned with those parameters, it may take a longer time to get your proposal accepted and your data stored. To improve acceptance rate for your storage deal proposals, here is a quick guide:

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-d48ad127-7fff-1a85-0e13-45f85f7764d0"><div dir="ltr" style="margin-left:0pt;" align="left">

  | Funds in Contract ($ per TiB per year) | Minimum Deal Size
-- | -- | --
If you have datacap (verified deals) | $0 | 512 MB (4GB preferred)
If you don’t have datacap (unverified deals) | $240 (approx 40 FIL) | 512 MB (4GB preferred)

</div></b>

Apply for datacap verification on the [Filecoin mainnet](https://filplus.info/) (choose Automatic Verification for deal sizes <32GB and General Verification for deal sizes >32GB) and the [Hyperspace testnet](https://hyperspace.yoga/#notary).

### CODE REVIEW

**Comment by trruckerfling** [comment]
Missing links from new client contract and deal bounty tutorial

**Comment by aashidham** [comment]
Tutorial for client contract currently here: https://github.com/filecoin-project/fvm-starter-kit-deal-making

To be made public on launch date

**Comment by aashidham** [comment]
Notion doc here if you have comments / updates: https://www.notion.so/pl-strflt/FVM-Deal-Making-9180651d57334279a24f3e9786d44c66

**Comment by trruckerfling** [comment]
FYI referenced your notion doc @aashidham so the info is consistent from docs to unified repo readme

**Comment by ElPaisano** [comment]
@trruckerfling this PR is showing 158 files changed... can you help me to understand what this PR does and why 158 files are being changed? That's a ton of files.

**Comment by ElPaisano** [comment]
Per discussion with @trruckerfling, I am recreating this PR in https://github.com/filecoin-project/filecoin-docs/pull/1790, so we can close this

**Pull request closed without merging**
