### PR TITLE
Display image based on dark or light mode.

### PR DESCRIPTION
**Pull request by ac12644**
Added white background to the image.

### CODE REVIEW

**Comment by ac12644** [comment]
This pull request is created to fix image issue on https://docs.filecoin.io/get-started/store-and-retrieve/set-up/

Screenshot 2022-10-06 at 22 14 06

**Comment by johnnymatthews** [comment]
Thanks for this PR! I'm wondering if there's a way to show a particular image based on whether the theme is in dark mode or not; similar to how we show either a dark or light text logo for this repo's README.md.

Screen Shot 2022-10-11 at 10 32 09 AM

**Comment by ac12644** [comment]
if there is a prop for a dark or light theme then two images can be rendered one for light and one for dark but it has to be SVG format.

**Comment by ac12644** [comment]
Or what I can do is recreate these images in sketch and then upload it for both dark and light

**Comment by johnnymatthews** [comment]
> Or what I can do is recreate these images in sketch and then upload it for both dark and light

Or just invert the original image to create the white version. If you can do that, I'll look into how to display the correct image based on dark-mode/light-mode.

**Comment by ac12644** [comment]
Hi please check, if this code will work or not, 
```html
<picture align=center>
  <source media="(prefers-color-scheme: dark)" srcset="end-to-end-process-dark.png">
  <source media="(prefers-color-scheme: light)" srcset="end-to-end-process-light.png">
  <img alt="end-to-end-process" src="end-to-end-process.png">
 </picture>
```

**Comment by johnnymatthews** [comment]
It does! However, the images still have fixed backgrounds in them:

image

It'd be better to revert back to using the PNG with a transparent background, and just flip that between the dark and light themes. That way, each image will pick up the regular background colour from the website.

**Comment by johnnymatthews** [comment]
Oh gotcha! Sorry, I was looking at the wrong image file. It looks like the map PNG at the top has a transparent background, but that large arrow stuff doesn't. I'll recreate the image and push them into this PR.

**Comment by johnnymatthews** [comment]
There we go, I think that should do it.

**Comment by ac12644** [comment]
great

**Comment by johnnymatthews** [comment]
Just went through the build and it looks like it's displaying the correct images. Nice work @ac12644!

**Review by johnnymatthews — APPROVED** [review]
Looks good!

**Pull request merged**
