### PR TITLE
Issue 1547 - Explain what actors and contracts are

### PR DESCRIPTION
**Pull request by ElPaisano**
Addresses https://github.com/filecoin-project/filecoin-docs/issues/1547

### CODE REVIEW

**Comment by ElPaisano** [comment]
@johnnymatthews this is ready for review. Two things:

1. Cloudflare pages is failing, not sure why cus I can't see the logs
2. I'm still pretty unclear what `SystemActor` actually does, so I left it with a `?`. Spec https://spec.filecoin.io/systems/filecoin_vm/sysactors/#section-systems.filecoin_vm.sysactors doesn't say much, and neither did the video originally linked on this page https://www.youtube.com/watch?v=9JbwbTPonv0

**Comment by johnnymatthews** [comment]
Pinged the Lotus team for clarification on `SystemActor`. I'm pretty sure it's just the actor that initializes the other actors, but I'll double-check.

**Comment by johnnymatthews** [comment]
Information I got from the team:

```
Um, it’s basically a no-op actor, honestly. It:

- has the information about the “manifest” of the other builtin actors in it — so basically the CIDs of all the other actor codes (but doesn’t actually use this for anything)
- it’s the sender of the 2 “system” messages we have in Filecoin — Cron and Reward. But, again, the System Actor itself doesn’t have any special information or logic, it’s just what we put as the sender when we say “do the thing” every epoch.
- It “initializes” the other builtin actors like the Market, Power actor, etc., but it did this before genesis. So not really something that happens today, and again no interesting logic in it. It does NOT initialize miners, multisigs, etc.

So all that to say…kinda does nothing [...] not important enough to go into detail. i can't ever imagine a user needing to know or care about the system actor
```

**Comment by ElPaisano** [comment]
@jo

> Information I got from the team:
> 
> ```
> Um, it’s basically a no-op actor, honestly. It:
> 
> - has the information about the “manifest” of the other builtin actors in it — so basically the CIDs of all the other actor codes (but doesn’t actually use this for anything)
> - it’s the sender of the 2 “system” messages we have in Filecoin — Cron and Reward. But, again, the System Actor itself doesn’t have any special information or logic, it’s just what we put as the sender when we say “do the thing” every epoch.
> - It “initializes” the other builtin actors like the Market, Power actor, etc., but it did this before genesis. So not really something that happens today, and again no interesting logic in it. It does NOT initialize miners, multisigs, etc.
> 
> So all that to say…kinda does nothing [...] not important enough to go into detail. i can't ever imagine a user needing to know or care about the system actor
> ```

@johnnymatthews RE `SystemActor`: Added https://github.com/filecoin-project/filecoin-docs/pull/1693/commits/7861a2f21dab19c62a2b75e1d9dcf37aa211faee for this

Other than that, is this good to merge?

**Review by johnnymatthews — APPROVED** [review]
This works!

**Pull request merged**
