### PR TITLE
Add simplified snapshot instructions

### PR DESCRIPTION
**Pull request by mishmosh**
Document the simplified chain snapshot option, implemented in https://github.com/filecoin-project/lotus/pull/3754.

Question for reviewers: it looks like most miners & clients can use the simplified snapshot, is that correct? If so I'll add a sentence recommending it even more strongly before merging.

### CODE REVIEW

**Comment by hsanjuan** [comment]
Ok for me if ribasushi approves.

**Review by ribasushi — CHANGES_REQUESTED** [review]
A number of parts of this advice are outdated, I'll supply an updated patch in a few, need to ask devteam for a detail.

In summary:
- the offline requirement is no longer a thing
- the linked snapshot should be different
- the order of preference should be reversed

fix incoming...

**Comment by hsanjuan** [comment]
@ribasushi bump

**Comment by hsanjuan** [comment]
I included this in #484

**Pull request closed without merging**
