### PR TITLE
WIP: Link to ProtoSchool's Verifying Storage on Filecoin tutorial

### PR DESCRIPTION
**Pull request by terichadbourne**
This PR drops links to the new Verifying Storage on Filecoin tutorial in the most relevant spots I can find where people may want to learn more about Filecoin proofs, Comms, etc.. I see very little in the docs on this topic right now and I may have missed something, so would appreciate feedback on other spots that make sense.

### CODE REVIEW

**Comment by terichadbourne** [comment]
@cwaring I tried copying the code for this callout feature from the IPFS site but it hasn't actually formatted itself. What do we need to do under the hood to display something similar to this: 

image

instead of the current: 

image

**Comment by har00ga** [comment]
@terichadbourne Oh derp, sorry about causing a merge conflict 😢 I moved the `mining.md` content to the `README.md` page in a PR earlier. All changes look good to me though!

**Comment by terichadbourne** [comment]
> sorry about causing a merge conflict 😢 I moved the mining.md content to the README.md page in a PR earlier.

I've resolved this conflict, so just awaiting guidance from @cwaring on how to get the formatting for callouts working.

**Comment by terichadbourne** [comment]
Thanks for fixing the callout display, @cwaring!

I've moved the callout on the making storage deals page to be more prominent given the importance for the audience on that page (and the detail the tutorial provides that's not covered in the docs site). 

Going to merge this to avoid more merge conflicts with so much activity in the repo, but happy to change placements or text of any of these callouts if folks who haven't yet reviewed feel something's out of place. 

Here are the current placements: 


**How tos > Store > Making Storage Deals**

image

**Mine > Uptime, Slashing & Penalties** 

image

**Why Filecoin > Verifiable Traces** 

image

**What is Filecoin? > For Users**

image

**Pull request merged**
