### PR TITLE
update filplus docs for network 13 upgrade

### PR DESCRIPTION
**Pull request by jennijuju**
Merge upon network v13 upgrade

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/store/filecoin-plus.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- The following link returned HTTP status code 301 (Moved Permanently):
  http://slingshot.filecoin.io/
- The following link returned HTTP status code 404 (Not Found):
  https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-methods.md
- The following link returned HTTP status code 301 (Moved Permanently):
  https://plus.fil.org/miners
- The following link returned HTTP status code 308 (Permanent Redirect):
  http://filrep.io/
- The following link returned HTTP status code 302 (Found):
  https://filecoinproject.slack.com/archives/C01DLAPKDGX
- This phrase is duplicated. You should probably leave only “Filecoin Plus”.
  ```
  # Filecoin Plus Filecoin Plus aims to enable the demand side of the F...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- This noun is normally spelled as one word.
  ```
  ...nity's most important information. Root Key Holders, Notaries, Clients, and ...
                                             ^^^^^^^^^^^
  ```
- This noun is normally spelled as one word.
  ```
  ...  (opens new window). If approved, Root Key Holders  (opens new window) (exe...
                                             ^^^^^^^^^^^
  ```
- The preposition ‘for’ seems more likely in this position.
  ```
  ...ested in becoming Notaries should apply to this role by filing an Issue in t...
                                             ^^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...incentivize miners to serve their needs - this can include providing additio...
                                             ^
  ```
- Possibly missing preposition found.
  ```
  ...it by sending a minimal amount of FILto it (purchasing some FIL from an exch...
                                             ^^
  ```
- Insert a space between the numerical value and the unit symbol.
  ```
  ...uch a Notary, which is currently giving 32GiB of DataCap once every 30 days ...
                                             ^^^^^
  ```
- Insert a space between the numerical value and the unit symbol.
  ```
  .... For DataCap requirements greater than 32GiB - choose General Verification ...
                                             ^^^^^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...DataCap requirements greater than 32GiB - choose General Verification in Ste...
                                             ^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...s of requests they'll choose to support - it is recommended that you select ...
                                             ^
  ```
- Did you mean “them”?
  ```
  ...a miner to take a FIL+ storage deal: In the For Clients section of the Filec...
                                             ^^^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...calls, which happen every other Tuesday - use the Filecoin Community Events ...
                                             ^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/store/filecoin-plus.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- The following link returned HTTP status code 301 (Moved Permanently):
  http://slingshot.filecoin.io/
- The following link returned HTTP status code 404 (Not Found):
  https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-methods.md
- The following link returned HTTP status code 301 (Moved Permanently):
  https://plus.fil.org/miners
- The following link returned HTTP status code 308 (Permanent Redirect):
  http://filrep.io/
- The following link returned HTTP status code 302 (Found):
  https://filecoinproject.slack.com/archives/C01DLAPKDGX
- This phrase is duplicated. You should probably leave only “Filecoin Plus”.
  ```
  # Filecoin Plus Filecoin Plus aims to enable the demand side of the F...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- This noun is normally spelled as one word.
  ```
  ...nity's most important information. Root Key Holders, Notaries, Clients, and ...
                                             ^^^^^^^^^^^
  ```
- This noun is normally spelled as one word.
  ```
  ...  (opens new window). If approved, Root Key Holders  (opens new window) (exe...
                                             ^^^^^^^^^^^
  ```
- The preposition ‘for’ seems more likely in this position.
  ```
  ...ested in becoming Notaries should apply to this role by filing an Issue in t...
                                             ^^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...incentivize miners to serve their needs - this can include providing additio...
                                             ^
  ```
- Possibly missing preposition found.
  ```
  ...it by sending a minimal amount of FILto it (purchasing some FIL from an exch...
                                             ^^
  ```
- Insert a space between the numerical value and the unit symbol.
  ```
  ...uch a Notary, which is currently giving 32GiB of DataCap once every 30 days ...
                                             ^^^^^
  ```
- Insert a space between the numerical value and the unit symbol.
  ```
  .... For DataCap requirements greater than 32GiB - choose General Verification ...
                                             ^^^^^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...DataCap requirements greater than 32GiB - choose General Verification in Ste...
                                             ^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...s of requests they'll choose to support - it is recommended that you select ...
                                             ^
  ```
- Did you mean “them”?
  ```
  ...a miner to take a FIL+ storage deal: In the For Clients section of the Filec...
                                             ^^^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...calls, which happen every other Tuesday - use the Filecoin Community Events ...
                                             ^
  ```

**Review by dkkapur — APPROVED** [review]
Looks great, thanks @jennijuju

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/store/filecoin-plus.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- The following link returned HTTP status code 301 (Moved Permanently):
  http://slingshot.filecoin.io/
- The following link returned HTTP status code 404 (Not Found):
  https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-methods.md
- The following link returned HTTP status code 301 (Moved Permanently):
  https://plus.fil.org/miners
- The following link returned HTTP status code 308 (Permanent Redirect):
  http://filrep.io/
- The following link returned HTTP status code 302 (Found):
  https://filecoinproject.slack.com/archives/C01DLAPKDGX
- This phrase is duplicated. You should probably leave only “Filecoin Plus”.
  ```
  # Filecoin Plus Filecoin Plus aims to enable the demand side of the F...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- This noun is normally spelled as one word.
  ```
  ...nity's most important information. Root Key Holders, Notaries, Clients, and ...
                                             ^^^^^^^^^^^
  ```
- This noun is normally spelled as one word.
  ```
  ...  (opens new window). If approved, Root Key Holders  (opens new window) (exe...
                                             ^^^^^^^^^^^
  ```
- The preposition ‘for’ seems more likely in this position.
  ```
  ...ested in becoming Notaries should apply to this role by filing an Issue in t...
                                             ^^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...incentivize miners to serve their needs - this can include providing additio...
                                             ^
  ```
- Possibly missing preposition found.
  ```
  ...it by sending a minimal amount of FILto it (purchasing some FIL from an exch...
                                             ^^
  ```
- Insert a space between the numerical value and the unit symbol.
  ```
  ...uch a Notary, which is currently giving 32GiB of DataCap once every 30 days ...
                                             ^^^^^
  ```
- Insert a space between the numerical value and the unit symbol.
  ```
  .... For DataCap requirements greater than 32GiB - choose General Verification ...
                                             ^^^^^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...DataCap requirements greater than 32GiB - choose General Verification in Ste...
                                             ^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...s of requests they'll choose to support - it is recommended that you select ...
                                             ^
  ```
- Did you mean “them”?
  ```
  ...a miner to take a FIL+ storage deal: In the For Clients section of the Filec...
                                             ^^^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...calls, which happen every other Tuesday - use the Filecoin Community Events ...
                                             ^
  ```

**Comment by johnnymatthews** [comment]
Made a few minor changes. Assuming @filecorgi is happy with everything, you can merge when ready :)

**Review by johnnymatthews — APPROVED** [review]

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/store/filecoin-plus.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- The following link returned HTTP status code 301 (Moved Permanently):
  http://slingshot.filecoin.io/
- The following link returned HTTP status code 404 (Not Found):
  https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-methods.md
- The following link returned HTTP status code 301 (Moved Permanently):
  https://plus.fil.org/miners
- The following link returned HTTP status code 308 (Permanent Redirect):
  http://filrep.io/
- The following link returned HTTP status code 302 (Found):
  https://filecoinproject.slack.com/archives/C01DLAPKDGX
- This phrase is duplicated. You should probably leave only “Filecoin Plus”.
  ```
  # Filecoin Plus Filecoin Plus aims to enable the demand side of the F...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- Did you mean “them”?
  ```
  ...a miner to take a FIL+ storage deal: In the For Clients section of the Filec...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ... are willing to take Fil+ storage deals Use a Miner Reputation system such a...
                                             ^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ... storage miners who can meet your needs Join the #fil-plus  (opens new windo...
                                             ^^^^
  ```

**Pull request merged**
