### PR TITLE
Overhaul pre-commit script to use Vale

### PR DESCRIPTION
**Pull request by ElPaisano**
This PR overhauls the current pre-commit linter set up. 

## Details:

- replaces [mdspell](https://www.npmjs.com/package/markdown-spellcheck) with [vale](https://vale.sh/). See [Why](#why) below
- adds emojis 💯 🥇 (we can add more)

The other linters, markdownlint-cli2 (for MD formatting) and markdown-link-check (for broken links), are still used. 

## Why

In the first iteration of the pre-commit check, we used [mdspell](https://www.npmjs.com/package/markdown-spellcheck), which allowed us to check for spelling errors against a standard American English dictionary and a custom file of Fil-specific words, as well as interactively walk through and fix flagged spelling errors in the command line. 

However, there were a few notable problems:
- mdspell flags all sorts of things it shouldn't, like code blocks and CIDs.
- The Interactive spelling feature was slow, inconsistent, and would often just hang if it got stuck on a really long string
- There was no way to add regex patterns, so the vocab list was becoming too big to manage
- There was no way to check for actual writing style, just spelling 

With vale, we lose interactive spelling fix functionality, but gain the following:
- way better performance
- regex support
- the ability to check for writing style against custom style rules and/or an industry-standard guide like https://vale.sh/hub/microsoft/
- metrics like Flesch Kincaid Reading Score
- customizability
- Great docs and open source community around Vale

## Todo

- [ ] Update filecoin-docs README linter instructions
- [ ] Sync with EngResDocs to determine if we want to use an existing style guide or implement Vale rules to mirror our existing guide in https://docs.filecoin.io/basics/project-and-community/ways-to-contribute/
- [ ] Have one or two folks dogfood this and see what they think

### CODE REVIEW

**Comment by ElPaisano** [comment]
Note that https://github.com/filecoin-project/filecoin-docs/tree/48a859e99154ed88b3aaae7b2c42bbad8c0a6616/styles is where all of the custom writing style rules and words are defined.

In the real world, we would replace these sample rules with our own rules or another, more extensive guide, like MSFT or Redhat

**Comment by johnnymatthews** [comment]
Ran into a couple problems. First, `pre-commit` needs to be installed. `npm install -g pre-commit` didn't work for some reason, so I used `brew install pre-commit` instead. I also had to install Go version `1.20` since that's a dep of pre-commit apparently.

Once it ran, it was pretty smooth. Although I did hit some weird quirks:

- Vale wanted to change `Cryptocurrency` to `cryptocurrency` which is an incorrect suggestion since `Cryptocurrency` is at the start of a sentence.
- Vale doesn't like the word _tooltip_, which is only ever used in the context of the tooltip shortcode: `{{< tooltip CID >}}` for example.
- Vale missed the typo `conatns`; should be `contains`. Not really sure what's going on here.

Screenshot 2023-07-17 at 11 55 36

**Comment by ElPaisano** [comment]
@johnnymatthews thanks for test running. I fixed the following:

- Vale is now configure to ignore Hugo tooltips and anything in them, so it doesn't flag that
- Updated the dictionary to allow "cryptocurrency" with a cap "C" as well
- package-lock.json is showing pre-commit as a dependcy. Which means that you shouldnt have to install it separately, it should just install when, say , a new contributor clones down the repo and runs `npm install`

 a few things to note here:
 
1. To get this to work the way we want it to, we need to:
   1. Pick a style guide
   1. Iron out acceptable terminology

**Comment by johnnymatthews** [comment]
Closing due to switch to GitBook. We'll revisit the automation created in this PR in the near future.

**Pull request closed without merging**
