### PR TITLE
[chore]: add  gelato guide for relay and w3f

### PR DESCRIPTION
**Pull request by anirudhmakhana**

### CODE REVIEW

**Comment by smagdali** [comment]
@anirudhmakhana https://app.gelato.app is coming up as a broken link...

**Comment by eshon** [comment]
I think @anirudhmakhana meant to use https://app.gelato.network/  there?

**Comment by anirudhmakhana** [comment]
Hi @smagdali @eshon yes, i meant to use app.gelato.network, must be a typo

**Comment by longfeiWan9** [comment]
@anirudhmakhana @smagdali this PR is not fully completed because there were missing links to add those two pages into navigation bar so they were not listed in the navigation? @anirudhmakhana can you please create another PR to add the links?

**Pull request merged**
