### PR TITLE
feat: add task completion survey banner

### PR DESCRIPTION
**Pull request by zebateira**
This PR adds the task completion survey banner.
The banner shows in all pages.
I'm not sure about the styling so any feedback is welcome!

image

/cc @atopal 

For similar implementations see:

- https://github.com/ipfs/ipfs-website/pull/82
- https://github.com/ipfs/ipfs-docs/pull/849

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by atopal** [comment]
I'm not so sure about pushing down the content on each docs page. What about putting it as an overlay into the top right corner?

**Comment by zebateira** [comment]
@atopal what do you mean by overlay?

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by johnnymatthews** [comment]
It doesn't look like we're gonna be implementing this anytime soon. Gonna close for now.

**Pull request closed without merging**
