### PR TITLE
Adds missing warning about unauditied wallets.

### PR DESCRIPTION
**Pull request by johnnymatthews**
This warning _did_ exist at some point, but it's got lost somewhere. This PR adds a warning to the wallets section pointing out that unaudited wallets are potentially dangerous and should be used with caution.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/about-filecoin/managing-assets.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://filwallet.ai
- Possibly missing comma found.
  ```
  ...tegrated with a Ledger hardware device. Yes FilSnap MetaMask plugin MetaMask...
                                             ^^^
  ```
- Possibly missing comma found.
  ```
  ... A multi-currency wallet. Unknown Trust wallet A multi-currency wallet. This...
                                             ^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...cryptocurrency exchange, or simply just exchange is a service that lets you ...
                                             ^^^^^^^^
  ```
- ‘make a decision’ might be wordy. Consider a shorter alternative.
  ```
  ...encies. You can use these lists to help make a decision on which exchange to...
                                             ^^^^^^^^^^^^^^^
  ```
- As a shorter alternative for ‘able to’, consider using “can”.
  ```
  ... account. However, most large exchanges are able to verify your information ...
                                             ^^^^^^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/about-filecoin/managing-assets.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://filwallet.ai
- Possibly missing comma found.
  ```
  ...tegrated with a Ledger hardware device. Yes FilSnap MetaMask plugin MetaMask...
                                             ^^^
  ```
- Possibly missing comma found.
  ```
  ... A multi-currency wallet. Unknown Trust wallet A multi-currency wallet. This...
                                             ^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/about-filecoin/managing-assets.md`:
- Possibly missing comma found.
  ```
  ...tegrated with a Ledger hardware device. Yes FilSnap MetaMask plugin MetaMask...
                                             ^^^
  ```
- Possibly missing comma found.
  ```
  ... A multi-currency wallet. Unknown Trust wallet A multi-currency wallet. This...
                                             ^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/about-filecoin/managing-assets.md`:
- Possibly missing comma found.
  ```
  ...tegrated with a Ledger hardware device. Yes FilSnap MetaMask plugin MetaMask...
                                             ^^^
  ```
- Possibly missing comma found.
  ```
  ... A multi-currency wallet. Unknown Trust wallet A multi-currency wallet. This...
                                             ^^^^^^
  ```

**Review by jennijuju — APPROVED** [review]

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/about-filecoin/managing-assets.md`:
- Possibly missing comma found.
  ```
  ...tegrated with a Ledger hardware device. Yes FilSnap MetaMask plugin MetaMask...
                                             ^^^
  ```
- Possibly missing comma found.
  ```
  ... A multi-currency wallet. Unknown Trust wallet A multi-currency wallet. This...
                                             ^^^^^^
  ```

**Pull request merged**
