### PR TITLE
add FoxWallet link

### PR DESCRIPTION
**Pull request by icodeface**

### CODE REVIEW

**Comment by johnnymatthews** [comment]
Why should we add this wallet into Filecoin docs?

**Comment by icodeface** [comment]
> Why should we add this wallet into Filecoin docs?

hi, what's the problem ? 
It supports Filecoin as the main coin, and provides useful information about the Filecoin network. The wallet is made by [filfox](https://filfox.info/) which is one of the most popular Filecoin explorer, and it is [audited](https://www.certik.org/projects/fox-wallet).

**Comment by icodeface** [comment]
@johnnymatthews here are some screenshots you can take a look:
image
image
image
image
image

**Comment by johnnymatthews** [comment]
Ok cool, thanks for sharing. We'll look into the wallet now and decide where it should go into the Filecoin docs.

**Comment by icodeface** [comment]
> Ok cool, thanks for sharing. We'll look into the wallet now and decide where it should go into the Filecoin docs.

thank you

**Comment by johnnymatthews** [comment]
I'm finally getting around to merging this. Sorry for the _huge_ delay.

**Pull request merged**
