### PR TITLE
Add estuary to store, build and reference.

### PR DESCRIPTION
**Pull request by jennijuju**

### CODE REVIEW

**Comment by filecorgi** [comment]
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ciskip]` in this PR for details.
- Vuepress build failed...

```

> filecoin-docs@1.0.0 docs:build /home/runner/work/filecoin-docs/filecoin-docs
> npm run docs:links && vuepress build docs


> filecoin-docs@1.0.0 docs:links /home/runner/work/filecoin-docs/filecoin-docs
> vuepress check-md docs


Checking markdown...

2 dead links was found

  Hash is not found: [Filecoin's economy](#filecoins-economy) (/home/runner/work/filecoin-docs/filecoin-docs/docs/reference/README.md:15:7)
  File is not found: [Staging Zone]((#staging-zone) (/home/runner/work/filecoin-docs/filecoin-docs/docs/store/estuary.md:42:40)

Executes with --fix to fix automatically

Checking failed

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:links: `vuepress check-md docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:links script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-05-28T23_09_20_823Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:build: `npm run docs:links && vuepress build docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-05-28T23_09_20_841Z-debug.log
```

**Comment by filecorgi** [comment]
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ciskip]` in this PR for details.
- Vuepress build failed...

```

> filecoin-docs@1.0.0 docs:build /home/runner/work/filecoin-docs/filecoin-docs
> npm run docs:links && vuepress build docs


> filecoin-docs@1.0.0 docs:links /home/runner/work/filecoin-docs/filecoin-docs
> vuepress check-md docs


Checking markdown...

2 dead links was found

  Hash is not found: [Filecoin's economy](#filecoins-economy) (/home/runner/work/filecoin-docs/filecoin-docs/docs/reference/README.md:15:7)
  File is not found: [Staging Zone]((#staging-zone) (/home/runner/work/filecoin-docs/filecoin-docs/docs/store/estuary.md:42:40)

Executes with --fix to fix automatically

Checking failed

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:links: `vuepress check-md docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:links script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-05-28T23_11_48_616Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:build: `npm run docs:links && vuepress build docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-05-28T23_11_48_635Z-debug.log
```

**Comment by jimmylee** [comment]
This is perfect! Thank you LGTM

**Review by jimmylee — APPROVED** [review]
LGTM

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```

> filecoin-docs@1.0.0 docs:build /home/runner/work/filecoin-docs/filecoin-docs
> npm run docs:links && vuepress build docs


> filecoin-docs@1.0.0 docs:links /home/runner/work/filecoin-docs/filecoin-docs
> vuepress check-md docs


Checking markdown...

2 dead links was found

  Hash is not found: [Filecoin's economy](#filecoins-economy) (/home/runner/work/filecoin-docs/filecoin-docs/docs/reference/README.md:15:7)
  File is not found: [Staging Zone]((#staging-zone) (/home/runner/work/filecoin-docs/filecoin-docs/docs/store/estuary.md:42:40)

Executes with --fix to fix automatically

Checking failed

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:links: `vuepress check-md docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:links script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-05-29T01_58_37_914Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:build: `npm run docs:links && vuepress build docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-05-29T01_58_37_930Z-debug.log
```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```

> filecoin-docs@1.0.0 docs:build /home/runner/work/filecoin-docs/filecoin-docs
> npm run docs:links && vuepress build docs


> filecoin-docs@1.0.0 docs:links /home/runner/work/filecoin-docs/filecoin-docs
> vuepress check-md docs


Checking markdown...

1 dead links was found

  File is not found: [Staging Zone]((#staging-zone) (/home/runner/work/filecoin-docs/filecoin-docs/docs/store/estuary.md:38:40)

Executes with --fix to fix automatically

Checking failed

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:links: `vuepress check-md docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:links script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-05-29T02_18_19_126Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filecoin-docs@1.0.0 docs:build: `npm run docs:links && vuepress build docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filecoin-docs@1.0.0 docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-05-29T02_18_19_140Z-debug.log
```

**Review by johnnymatthews — APPROVED** [review]
Made some changes and fixed a couple links. We should have a stand-alone page for Estuary instead of two, but we can deal with that later.

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/build/estuary.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- The noun “invitation” is usually used instead of ‘invite’ in formal writing.
  ```
  ...lic release. However, you can reqest an invite  (opens new window) to test t...
                                             ^^^^^^
  ```
- The official name of this software platform is spelled with a capital “H”.
  ```
  ...e deals. # Additional resources Estuary Github repository  (opens new window...
                                             ^^^^^^
  ```

### `docs/store/estuary.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://networks.filecoin.io
- The following link returned HTTP status code 301 (Moved Permanently):
  http://slingshot.filecoin.io/
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... on the Filecoin network: Go to Estuary.tech  (opens new window) and log in....
                                             ^^^^
  ```
- This phrase is duplicated. You should probably leave only “Your Data”.
  ```
  ... stored on Filecoin Network. # Retrieve Your Data Your data is retrievable a...
                                             ^^^^^^^^^^^^^^^^^^^
  ```
- Using many exclamation marks might seem excessive (in this case: 4 exclamations marks for a text that’s 2424 characters long)
  ```
  ...ink under RETRIEVAL CID to get your data! # Additional resources Estuary Git...
                                             ^
  ```
- The official name of this software platform is spelled with a capital “H”.
  ```
  ...ur data! # Additional resources Estuary Github repository  (opens new window...
                                             ^^^^^^
  ```

**Pull request merged**
