### PR TITLE
Migration of Filecoin docs to the Doks Hugo site package. ciskip

### LINKED ISSUE #1161: Remove VuePress and use the Doks package.
Documentation sites maintained by Protocol Labs are being migrated to use the [Doks](getdoks.org) Hugo site package.

## Tasks

- [x] Move content over to Doks theme.
- [x] Update font to Filecoin docs default.\
- [x] Fill out the homepage.
- [x] Left nav fix (no menus on subpages)
- [x] Right nav fix (no "On this page" navigation)
- [x] Figure out dead nav items (some areas are blank, like Software -- should we just pull it?)
- [x] Figure out what do to with section index content (it currently shows up as sub-item because tier 1 nav links do not load pages on click)
- [x] Convert `:::tip` instances to use `alert` shortcode
- [x] Migrate links to be Hugonic and use `relref`
- [x] Lotus logos abound in `/static` directory
- [x] Allow sections in topbar nav.
- [x] Enable search across site.
- [x] Create sidebar menus for each topbar section. (as seen here: https://github.com/atwriter/new_doks_site/pull/1/commits/40e6eae81a8748645525afadf21b1759ce5f2c77)
    - [x] About Filecoin
    - [x] Networks
    - [x] Get started
    - [x] Store
    - [x] Storage provider
    - [x] Build
    - [x] Reference
- [x] Remove `{{ $frontmatter.title }}` and `{{ $frontmatter.description }}`
- [x] Replicate the docs.filecoin.io homepage.
- [x] Order the sidebar to fit docs.filecoin.io
- [ ] Move images back into [page bundles](https://gohugo.io/content-management/page-bundles/)
- [ ] Topbar logo should use sans-serif font. No idea where this times-new-roman has come from...
- [ ] Topbar nav should highlight which section we're in.

### PR DESCRIPTION
**Pull request by johnnymatthews**
Continuation of #1144.

---

Implements URL-neutral migration (no redirects needed) by breaking out of the "/docs" box imposed by DOKS theme.

Closes #1161

Task list in https://github.com/filecoin-project/filecoin-docs/issues/1161

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Hugo build failed...

```

> @hyas/doks@0.3.4 prebuild
> npm run clean


> @hyas/doks@0.3.4 clean
> shx rm -rf public resources

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'concat-map'
Require stack:
- /home/runner/work/filecoin-docs/filecoin-docs/node_modules/brace-expansion/index.js
- /home/runner/work/filecoin-docs/filecoin-docs/node_modules/minimatch/minimatch.js
- /home/runner/work/filecoin-docs/filecoin-docs/node_modules/glob/glob.js
- /home/runner/work/filecoin-docs/filecoin-docs/node_modules/shelljs/src/common.js
- /home/runner/work/filecoin-docs/filecoin-docs/node_modules/shelljs/shell.js
- /home/runner/work/filecoin-docs/filecoin-docs/node_modules/shx/lib/shx.js
- /home/runner/work/filecoin-docs/filecoin-docs/node_modules/shx/lib/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/work/filecoin-docs/filecoin-docs/node_modules/brace-expansion/index.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/filecoin-docs/filecoin-docs/node_modules/brace-expansion/index.js',
    '/home/runner/work/filecoin-docs/filecoin-docs/node_modules/minimatch/minimatch.js',
    '/home/runner/work/filecoin-docs/filecoin-docs/node_modules/glob/glob.js',
    '/home/runner/work/filecoin-docs/filecoin-docs/node_modules/shelljs/src/common.js',
    '/home/runner/work/filecoin-docs/filecoin-docs/node_modules/shelljs/shell.js',
    '/home/runner/work/filecoin-docs/filecoin-docs/node_modules/shx/lib/shx.js',
    '/home/runner/work/filecoin-docs/filecoin-docs/node_modules/shx/lib/cli.js'
  ]
}
```

**Comment by filecorgi** [comment]
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ciskip]` in this PR for details.
- Hugo build was successful!

**Comment by yusefnapora** [comment]
This looks awesome! I noticed that search isn't working but saw in slack that you're aware.

I noticed a small typo on the home page but couldn't find it in the diff -

```
This is the place for conceptual Filecoin related content, while [lotus.filecoin.io](https://lotus.filecoin.io/) is where you're find installation instructions and guides for running a Lotus node.
```
"you're find" should be "you'll find"

Still clicking through - I'll comment if I find anything.

**Comment by filecorgi** [comment]
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ciskip]` in this PR for details.
- Hugo build was successful!

**Comment by filecorgi** [comment]
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ciskip]` in this PR for details.
- Hugo build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Hugo build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Hugo build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by johnnymatthews** [comment]
Hmm, we've got an issue with navigation on mobile. I'm in the **About Filecoin** section here, and this is the sidebar nav that's showing up in mobile:

image

It's wrong. It should show stuff like **Basics** > **What is Filecoin**, **How Filecoin works**, etc. I'm looking into this now.

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Hugo build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Hugo build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Hugo build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Hugo build was successful!

**Comment by johnnymatthews** [comment]
> With the mobile nav issue fixed 🎉, is there anything else blocking this merge? - @mishmosh 

Sorry for the delay here. This PR is not getting merged. But PR https://github.com/filecoin-project/filecoin-docs/pull/1198 IS! There's a bunch of issues with this PR for some reason. So I rebuilt this site from the ground up in #1198, and everything works! Turns out rebuilding a site from the base Doks theme is super quick once you know where everything has to go.

**Pull request closed without merging**
