### PR TITLE
Issue 1590 Update JSON-RPC calls to use mainnet

### PR DESCRIPTION
**Pull request by ElPaisano**
Addresses https://github.com/filecoin-project/filecoin-docs/issues/1590

### CODE REVIEW

**Comment by ElPaisano** [comment]
@johnnymatthews this is ready for review.

RE https://github.com/filecoin-project/filecoin-docs/issues/1590#issuecomment-1457288838, I went ahead and updated the JSON-RPC examples that I could find to use `https://api.node.glif.io`, and I assume this should hold for merge until FEVM deployment

**Comment by johnnymatthews** [comment]
Switching this PR to draft mode while the rest of the issues in https://github.com/filecoin-project/filecoin-docs/issues/1590 are being worked on.

**Comment by ElPaisano** [comment]
@johnnymatthews wondering what the status of this is now that https://github.com/filecoin-project/filecoin-docs/tree/feat/docs-information-restructure is going to be the new structure (this PR is a merge onto `main`)? Is this covered or superseded by work on that branch?

**Comment by ElPaisano** [comment]
After discussion, the best thing to do it to recreate this PR but against the feat/docs-information-restructure branch. Closing this. Superseded by https://github.com/filecoin-project/filecoin-docs/pull/1789

**Pull request closed without merging**
