### PR TITLE
Branding updates

### PR DESCRIPTION
**Pull request by ericronne**
Swaps in the correct Filecoin branding for all images.

ToDo: Update interface colors (no green eg), and redesign or recolor the landing-page graphic

### CODE REVIEW

**Comment by ericronne** [comment]
Closes #11

**Comment by filecorgi** [comment]
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ciskip]` in this PR for details.
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by ericronne** [comment]
Corrects logo and recolors top-nav vertical bar. Additional theming adjustments yet to come ([issue](https://github.com/filecoin-project/filecoin-docs/issues/11))

**Comment by johnnymatthews** [comment]
We good to merge this @ericronne ?

**Comment by ericronne** [comment]
Provided a front-ender such as @cwaring sees nothing amiss with it, yes let's. Thx.

**Comment by cwaring** [comment]
The blue logo looks really odd with the current teal theme, I would suggest that we also update the design in this PR before merging – but I also understand that is a bigger task that needs to be assigned to somebody.

**Comment by johnnymatthews** [comment]
I'm gonna merge this now. The logos we currently have are out of date, which isn't great. I'll make a new issue to _fix_ the teal colours on the homepage though.

**Pull request merged**
