### PR TITLE
Testing the language dropdown menu [ciskip]

### PR DESCRIPTION
**Pull request by johnnymatthews**
This was a fun one.

## What was wrong

So a while ago we, the Filecoin team, moved the **main** navigation from the topbar nav to the top of the sidebar nav.

Move forward about a year, and PR #1111 is trying to add ZH pages into Filecoin docs. But when we enable to language features built into VuePress, the **Language** dropdown ends up getting shoved to the side.

image

Not ideal.

## How to fix it

It turns out that all we did was force the the _mobile view_ for the sidebar nav to show all the time, and _hide_ the topbar nav.

image

So all we need to do is _hide_ the mobile-view sidebar nav when we're on desktop, and re-enable the topbar nav! This is pretty simple to do, as you can see by the file changes in the PR.

image

## What we should do next

We need to decide if we like the [layout presented in this PR](https://deploy-preview-1125--filecoin-docs.netlify.app/) _more_ that the layout that [docs.filecoin.io currently has](https://docs.filecoin.io). I personally like the layout presented in this PR, but we're not an army-of-one.

| [New layout](https://deploy-preview-1125--filecoin-docs.netlify.app) | [Old layout](https://docs.filecoin.io) |
| --- | --- |
| image | image |

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```

> filecoin-docs@1.0.0 docs:build
> npm run docs:links && vuepress build docs


> filecoin-docs@1.0.0 docs:links
> vuepress check-md docs


Checking markdown...

2 dead links was found

  File is not found: [Take a look now →](../store/README.md) (/home/runner/work/filecoin-docs/filecoin-docs/docs/zh/build/le-get-started.md:12:150)
  File is not found: ![Project ID and Project secret within Infura.](./images/get-started/infura-keys.png) (/home/runner/work/filecoin-docs/filecoin-docs/docs/zh/build/le-get-started.md:36:1)

Executes with --fix to fix automatically

Checking failed
```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```

> filecoin-docs@1.0.0 docs:build
> npm run docs:links && vuepress build docs


> filecoin-docs@1.0.0 docs:links
> vuepress check-md docs


Checking markdown...
Checking passed

wait Extracting site metadata...
tip Apply local theme at /home/runner/work/filecoin-docs/filecoin-docs/docs/.vuepress/theme...
tip Apply theme local (extends @vuepress/theme-default) ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin clean-urls (i.e. "vuepress-plugin-clean-urls") ...
tip Apply plugin @vuepress/google-analytics (i.e. "@vuepress/plugin-google-analytics") ...
tip Apply plugin code-copy (i.e. "vuepress-plugin-code-copy") ...
tip Apply plugin medium-zoom (i.e. "vuepress-plugin-medium-zoom") ...
tip Apply plugin seo (i.e. "vuepress-plugin-seo") ...
tip Apply plugin sitemap (i.e. "vuepress-plugin-sitemap") ...
tip Apply plugin robots (i.e. "vuepress-plugin-robots") ...
tip Apply plugin canonical (i.e. "vuepress-plugin-canonical") ...
tip Apply plugin check-md (i.e. "vuepress-plugin-check-md") ...
tip Apply plugin chunkload-redirect (i.e. "vuepress-plugin-chunkload-redirect") ...
tip Apply plugin ipfs (i.e. "vuepress-plugin-ipfs") ...
tip Apply plugin tabs (i.e. "vuepress-plugin-tabs") ...
[info] [webpackbar] Compiling Client
[info] [webpackbar] Compiling Server
Language does not exist: ~
[success] [webpackbar] Server: Compiled successfully in 13.02s
[success] [webpackbar] Client: Compiled successfully in 20.35s
wait Rendering static HTML...
[2K[1G
 SITEMAP  Generating sitemap...
error vuepress-plugin-sitemap apply generated failed.
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at dateFormatter (/home/runner/work/filecoin-docs/filecoin-docs/node_modules/vuepress-plugin-sitemap/index.js:24:60)
    at /home/runner/work/filecoin-docs/filecoin-docs/node_modules/vuepress-plugin-sitemap/index.js:69:13
    at Array.forEach (<anonymous>)
    at generated (/home/runner/work/filecoin-docs/filecoin-docs/node_modules/vuepress-plugin-sitemap/index.js:56:13)
    at AsyncOption.asyncApply (/home/runner/work/filecoin-docs/filecoin-docs/node_modules/@vuepress/core/lib/node/plugin-api/abstract/AsyncOption.js:33:21)
    at PluginAPI.applyAsyncOption (/home/runner/work/filecoin-docs/filecoin-docs/node_modules/@vuepress/core/lib/node/plugin-api/index.js:277:32)
    at Build.render (/home/runner/work/filecoin-docs/filecoin-docs/node_modules/@vuepress/core/lib/node/build/index.js:101:34)
    at async App.build (/home/runner/work/filecoin-docs/filecoin-docs/node_modules/@vuepress/core/lib/node/App.js:499:5)
```
- Check of `docs/zh/build/le-get-started.md` came back clean!

**Comment by johnnymatthews** [comment]
Ah, the logo goes a bit funky on screen sizes skinnier than 1240px. Gonna need to fix that: 
image

**Comment by dayou5168** [comment]
Great job~ Johny. I have difficulty in choosing

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```

> filecoin-docs@1.0.0 docs:build
> npm run docs:links && vuepress build docs


> filecoin-docs@1.0.0 docs:links
> vuepress check-md docs


Checking markdown...
Checking passed

wait Extracting site metadata...
tip Apply local theme at /home/runner/work/filecoin-docs/filecoin-docs/docs/.vuepress/theme...
tip Apply theme local (extends @vuepress/theme-default) ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin clean-urls (i.e. "vuepress-plugin-clean-urls") ...
tip Apply plugin @vuepress/google-analytics (i.e. "@vuepress/plugin-google-analytics") ...
tip Apply plugin code-copy (i.e. "vuepress-plugin-code-copy") ...
tip Apply plugin medium-zoom (i.e. "vuepress-plugin-medium-zoom") ...
tip Apply plugin seo (i.e. "vuepress-plugin-seo") ...
tip Apply plugin sitemap (i.e. "vuepress-plugin-sitemap") ...
tip Apply plugin robots (i.e. "vuepress-plugin-robots") ...
tip Apply plugin canonical (i.e. "vuepress-plugin-canonical") ...
tip Apply plugin check-md (i.e. "vuepress-plugin-check-md") ...
tip Apply plugin chunkload-redirect (i.e. "vuepress-plugin-chunkload-redirect") ...
tip Apply plugin ipfs (i.e. "vuepress-plugin-ipfs") ...
tip Apply plugin tabs (i.e. "vuepress-plugin-tabs") ...
[info] [webpackbar] Compiling Client
[info] [webpackbar] Compiling Server
Language does not exist: ~
[success] [webpackbar] Server: Compiled successfully in 13.08s
[success] [webpackbar] Client: Compiled successfully in 20.62s
wait Rendering static HTML...
[2K[1G
 SITEMAP  Generating sitemap...
error vuepress-plugin-sitemap apply generated failed.
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at dateFormatter (/home/runner/work/filecoin-docs/filecoin-docs/node_modules/vuepress-plugin-sitemap/index.js:24:60)
    at /home/runner/work/filecoin-docs/filecoin-docs/node_modules/vuepress-plugin-sitemap/index.js:69:13
    at Array.forEach (<anonymous>)
    at generated (/home/runner/work/filecoin-docs/filecoin-docs/node_modules/vuepress-plugin-sitemap/index.js:56:13)
    at AsyncOption.asyncApply (/home/runner/work/filecoin-docs/filecoin-docs/node_modules/@vuepress/core/lib/node/plugin-api/abstract/AsyncOption.js:33:21)
    at PluginAPI.applyAsyncOption (/home/runner/work/filecoin-docs/filecoin-docs/node_modules/@vuepress/core/lib/node/plugin-api/index.js:277:32)
    at Build.render (/home/runner/work/filecoin-docs/filecoin-docs/node_modules/@vuepress/core/lib/node/build/index.js:101:34)
    at async App.build (/home/runner/work/filecoin-docs/filecoin-docs/node_modules/@vuepress/core/lib/node/App.js:499:5)
```
- Check of `docs/zh/build/le-get-started.md` came back clean!

**Comment by johnnymatthews** [comment]
There's been some updates regarding this PR. 

Recently, the Protocol Labs docs team migrated the Lotus docs into it's own stand-alone site using the Hugo static-site generator. We've decided to move the Filecoin docs (this repo) to Hugo as well. This decision was made yesterday, and there's no plan as-of-yet.

With this in mind, we won't be adding the language dropdown into this repo **for now**.

**Pull request closed without merging**
