### PR TITLE
Foundry kit starter docs

### PR DESCRIPTION
**Pull request by xBalbinus**

### CODE REVIEW

**Comment by longfeiWan9** [comment]
@xBalbinus Sorry that the information is not clear on how to make updates for this issue. Please modify this PR before Johnny can review and merge it. 

- please checkout a new branch and merge it back to [feat/docs-information-restructure](https://github.com/filecoin-project/filecoin-docs/tree/feat/docs-information-restructure) which is for new structure of smart contract docs.
- foundry tutorial should go into [foundry folder](https://github.com/filecoin-project/filecoin-docs/blob/feat/docs-information-restructure/content/en/smart-contracts/developing-contracts/foundry/index.md)

**Comment by johnnymatthews** [comment]
It's alright @longfeiWan9, I'll make these changes to this PR now. Thanks for your help @xBalbinus!

**Comment by johnnymatthews** [comment]
Closed in favour of https://github.com/filecoin-project/filecoin-docs/pull/1786

**Comment by xBalbinus** [comment]
Thanks a ton!

**Pull request closed without merging**
